import type { Metadata } from "next";
import Link from "next/link";
import PageHeader from "../components/PageHeader";
import PrivacyPreferencesButton from "../components/PrivacyPreferencesButton";
import { PRIVACY_CONTACTS } from "@/lib/privacy";
import { createPageMetadata } from "@/lib/seo";

export const metadata: Metadata = createPageMetadata({ title: "Cookie Policy", description: "Cookie e tecnologie analoghe utilizzati dal portale Il Fanta a 20.", path: "/cookie-policy" });

const sections = [
  { title: "1. Cosa sono cookie e tecnologie simili", content: <p>I cookie sono piccoli dati che un sito o un servizio salva nel browser. Tecnologie analoghe, come il <code>localStorage</code>, possono conservare preferenze o identificativi sul dispositivo. Alcune sono necessarie al funzionamento; altre servono per misurazione o pubblicità e richiedono una scelta dell’utente quando previsto.</p> },
  { title: "2. Cookie tecnici e necessari", content: <><p>Supabase Auth usa cookie di sessione necessari per registrazione, accesso, sicurezza e mantenimento dell’account. Il sito può inoltre usare dati tecnici per protezione da abusi e continuità del servizio.</p><p>Queste tecnologie non sono usate per scegliere annunci personalizzati e, quando strettamente necessarie, non dipendono dal consenso pubblicitario.</p></> },
  { title: "3. Memoria locale e preferenze", content: <><p>L’Arcade usa <code>localStorage</code> per un identificativo casuale del giocatore, nickname, record personali, progressi, versione dei dati e migliori risultati per squadra. Le notifiche degli emblemi salvano localmente gli elementi già mostrati.</p><p>Questi dati restano sul dispositivo finché vengono cancellati dal sito, dal browser o dall’utente. Bloccando la memoria locale alcune preferenze o progressi potrebbero non persistere, ma il gioco prevede fallback dove tecnicamente possibile.</p></> },
  { title: "4. Google Analytics", content: <><p>Google Analytics misura utilizzo e prestazioni del sito e può raccogliere informazioni su sessioni, pagine, dispositivo e posizione approssimativa tramite cookie o identificatori. La durata effettiva dipende dalla configurazione Analytics e dalle tecnologie applicate da Google.</p><p>Dove richiesto, l’uso dello storage Analytics deve essere subordinato alle scelte raccolte dalla CMP e trasmesse mediante Consent Mode.</p></> },
  { title: "5. Google AdSense", content: <><p>Google AdSense può usare cookie e identificatori per pubblicare e misurare annunci, limitare ripetizioni, prevenire frodi e, se autorizzato, personalizzare la pubblicità. Anche partner pubblicitari selezionati nella piattaforma possono partecipare al trattamento.</p><p>Non viene promesso che gli annunci siano sempre personalizzati o sempre non personalizzati: il comportamento dipende dal consenso, dalla località, dalle impostazioni AdSense e dalle opzioni disponibili.</p></> },
  { title: "6. CMP Google", content: <><p>Per SEE, Regno Unito e Svizzera il sito prevede l’uso della CMP certificata Google configurata in AdSense “Privacy e messaggi”. La CMP mostra le categorie, i fornitori, le finalità e le durate disponibili dinamicamente, consentendo di accettare, rifiutare o gestire le opzioni.</p><p>Per questo motivo non viene riportato un elenco statico completo di cookie pubblicitari: nomi e durate possono cambiare in base a fornitore, configurazione, consenso e aggiornamenti tecnici.</p></> },
  { title: "7. Servizi e domini terzi", content: <p>Le tecnologie descritte possono essere fornite da Supabase e Google e, per infrastruttura e log tecnici, da Vercel. Aprendo link verso Instagram o TikTok si lascia il sito e si applicano le policy del servizio visitato; il portale non incorpora attualmente i loro contenuti nelle pagine.</p> },
  { title: "8. Browser e cancellazione", content: <><p>Le impostazioni del browser permettono di vedere, bloccare o cancellare cookie e dati locali. Il blocco dei cookie necessari può impedire accesso e funzioni account; la cancellazione del <code>localStorage</code> può azzerare preferenze e progressi Arcade presenti solo sul dispositivo.</p><p>Per ulteriori informazioni sul trattamento dei dati consulta l’<Link href="/privacy" className="font-black text-blue-800 underline">Informativa Privacy</Link>.</p></> },
];

export default function CookiePolicyPage() { return <main className="mx-auto w-full max-w-6xl px-4 py-7 sm:px-5 sm:py-12 lg:px-6 lg:py-16"><PageHeader eyebrow="Cookie e tecnologie analoghe" title="Cookie Policy" description="Quali tecnologie usa Il Fanta a 20 e come controllare le proprie preferenze." /><div className="grid gap-3 sm:gap-4">{sections.map((section) => <section key={section.title} className="rounded-[1.5rem] border border-slate-200 bg-white/85 p-5 shadow-[0_14px_38px_rgba(15,23,42,.06)] sm:rounded-[1.75rem] sm:p-7"><h2 className="text-lg font-black uppercase leading-tight tracking-tight text-blue-950 sm:text-2xl">{section.title}</h2><div className="mt-3 space-y-3 text-sm font-semibold leading-6 text-slate-600 sm:text-base sm:leading-7">{section.content}</div></section>)}</div><section id="preferenze-privacy" className="mt-4 scroll-mt-24 rounded-[1.5rem] border border-blue-200 bg-blue-50 p-5 sm:p-7"><h2 className="text-lg font-black uppercase text-blue-950 sm:text-2xl">Gestisci preferenze privacy</h2><p className="mt-3 text-sm font-semibold leading-6 text-slate-600">Il pulsante riapre il pannello della CMP Google quando il messaggio europeo è stato configurato, pubblicato e caricato. Finché la CMP non è attiva, questa pagina resta il riferimento informativo e la gestione può essere effettuata tramite il browser.</p><PrivacyPreferencesButton className="mt-4 min-h-11 max-w-full rounded-xl bg-blue-950 px-4 text-sm font-black text-white" /></section><p className="mt-6 text-xs font-black uppercase tracking-[.12em] text-slate-500">Ultimo aggiornamento: {PRIVACY_CONTACTS.ultimoAggiornamento}</p></main>; }
