"use client";

import Image from "next/image";
import Link from "next/link";
import { useEffect, useMemo, useRef, useState, useSyncExternalStore, useTransition } from "react";
import type { CSSProperties, ReactNode } from "react";
import OfficialAccountBadge from "@/app/account/OfficialAccountBadge";
import { clampExactScore, confirmRoundBetId, consistencyBlockProgress, countdownParts, currentStreakPresentation, filterLeaderboard, isCompletePrediction, isSubmitButtonDisabled, predictionOptions, searchLeaderboard, type LeaderboardFilter } from "@/lib/fantabet/ui";
import type { FantaBetBetView, FantaBetLeaderboardRow, FantaBetPageData, FantaBetPredictionRow, FantaBetStats, FantaBetTeam } from "@/lib/fantabet/server";
import type { FantaBetChoice } from "@/lib/fantabet/types";
import { scorePlay } from "@/lib/fantabet/logic";
import { confirmFantaBetSubmission, reopenFantaBetSubmission, saveFantaBetPrediction } from "./actions";

export default function FantaBetClient({ initial, demo = false, demoAvailable = false }: { initial: FantaBetPageData; demo?: boolean; demoAvailable?: boolean }) {
  const [predictions, setPredictions] = useState(initial.predictions);
  const [submission, setSubmission] = useState(initial.submission);
  const [editing, setEditing] = useState(!initial.submission);
  const [expanded, setExpanded] = useState<Set<number>>(() => new Set());
  const [confirmedBets, setConfirmedBets] = useState<Set<number>>(() => initial.submission ? new Set(initial.bets.map((bet) => bet.id)) : new Set());
  const [fullLeaderboard, setFullLeaderboard] = useState(false);
  const [now, setNow] = useState(() => new Date(initial.serverNow).getTime());
  const [submissionPending, startSubmission] = useTransition();
  const [submissionMessage, setSubmissionMessage] = useState("");
  const [needsReconfirmation, setNeedsReconfirmation] = useState(false);
  const betRefs = useRef(new Map<number, HTMLDivElement>());
  const hydrated = useSyncExternalStore(emptySubscribe, () => true, () => false);
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  const round = initial.round;
  const predictionByBet = useMemo(() => new Map(predictions.map((prediction) => [prediction.bet_id, prediction])), [predictions]);
  const roundBetIds = useMemo(() => new Set(initial.bets.map((bet) => bet.id)), [initial.bets]);
  const completed = initial.bets.filter((bet) => isCompletePrediction(bet.type, predictionByBet.get(bet.id))).length;
  if (!round) return <EmptyFantaBet leaderboard={initial.leaderboard} />;
  const requiredPredictions = round.requiredPredictions;
  const deadlinePassed = now >= new Date(round.deadlineAt).getTime();
  const preOpen = round.status === "pubblicata" && now < new Date(round.opensAt).getTime();
  const serverWindowOpen = round.status === "pubblicata" && !deadlinePassed && now >= new Date(round.opensAt).getTime();
  const writable = serverWindowOpen && editing;
  const confirmed = Boolean(submission) && !editing;
  const own = initial.leaderboard.find((row) => row.profile_id === initial.viewerId);
  const selectedIndex = initial.availableRounds.findIndex((item) => item.id === round.id);
  const previousRound = selectedIndex > 0 ? initial.availableRounds[selectedIndex - 1] : null;
  const nextRound = selectedIndex >= 0 && selectedIndex < initial.availableRounds.length - 1 ? initial.availableRounds[selectedIndex + 1] : null;
  const readOnlyRound = !serverWindowOpen;
  const currentRound = [...initial.availableRounds].reverse().find((item) => item.status === "pubblicata" && now < new Date(item.deadlineAt).getTime()) ?? null;
  const isCurrentRound = currentRound?.id === round.id;

  function saved(prediction: FantaBetPredictionRow) {
    setPredictions((current) => [...current.filter((item) => item.bet_id !== prediction.bet_id), prediction]);
    setSubmission(null);
    setConfirmedBets((current) => { const next = new Set(current); next.delete(prediction.bet_id); return next; });
  }
  function confirm() { if (demo) { setSubmission({ submittedAt: new Date().toISOString() }); setEditing(false); setNeedsReconfirmation(false); setSubmissionMessage("Schedina demo confermata"); return; } startSubmission(async () => { const result = await confirmFantaBetSubmission(round!.id); setSubmissionMessage(result.message); if (result.ok) { setSubmission({ submittedAt: result.submittedAt ?? new Date().toISOString() }); setEditing(false); setNeedsReconfirmation(false); } }); }
  function scrollToFirstBet() { const first = initial.bets[0]; if (first) window.requestAnimationFrame(() => betRefs.current.get(first.id)?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth", block: "center" })); }
  function reopen() { if (demo) { setSubmission(null); setEditing(true); setExpanded(new Set()); setConfirmedBets(new Set()); setNeedsReconfirmation(true); setSubmissionMessage("Schedina demo riaperta"); scrollToFirstBet(); return; } startSubmission(async () => { const result = await reopenFantaBetSubmission(round!.id); setSubmissionMessage(result.message); if (result.ok) { setSubmission(null); setEditing(true); setExpanded(new Set()); setConfirmedBets(new Set()); setNeedsReconfirmation(true); scrollToFirstBet(); } }); }
  function confirmPlay(betId: number) { if (!roundBetIds.has(betId)) return; setConfirmedBets((current) => confirmRoundBetId(current, betId, roundBetIds, requiredPredictions)); setExpanded((current) => { const next = new Set(current); next.delete(betId); return next; }); const index = initial.bets.findIndex((bet) => bet.id === betId); const next = initial.bets[index + 1]; if (next) window.requestAnimationFrame(() => betRefs.current.get(next.id)?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "auto" : "smooth", block: "center" })); }

  return <main className="min-h-screen overflow-x-hidden bg-[linear-gradient(180deg,#eaf4fc_0%,#fff_28%,#f8fafc_100%)] text-blue-950">
    <div className="mx-auto max-w-7xl px-3 py-5 sm:px-6 sm:py-9">
      {demoAvailable && !demo && <Link href="/fantabet?demo=1" className="mb-3 inline-flex rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-amber-800">Apri demo FantaBet</Link>}
      <header className="mb-5 border-b border-slate-200 pb-5">
        {demo && <div className="mb-3 inline-flex rounded-full bg-amber-100 px-3 py-1 text-[10px] font-black uppercase tracking-widest text-amber-800">Dati demo · solo development</div>}
        <div className="relative max-w-4xl lg:max-w-none"><p className="section-eyebrow">Pronostica e sfida gli altri</p><div className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="font-onder-title mt-2.5 text-4xl uppercase leading-none sm:mt-4 sm:text-6xl">Il FantaBet</h1><p className="mt-3 max-w-xl text-sm font-semibold leading-5 text-slate-600 sm:mt-6 sm:text-base sm:leading-8">Entra in Top 10 e conquista un posto per la prossima stagione!</p></div>{isCurrentRound && serverWindowOpen && <Countdown deadline={round.deadlineAt} now={now} />}</div></div>
      </header>
      <RoundNavigation rounds={initial.availableRounds} previous={previousRound} current={round.number} currentId={currentRound?.id ?? null} selectedId={round.id} next={nextRound} demo={demo} />
      {preOpen && <div role="status" className="mb-5 rounded-2xl border border-sky-200 bg-sky-50 p-4 text-center"><strong className="text-sm font-black uppercase text-blue-950">Schedina non ancora aperta</strong><p className="mt-1 text-xs font-bold text-slate-600">Le giocate apriranno il {new Date(round.opensAt).toLocaleString("it-IT")}.</p></div>}
      {!readOnlyRound && <div className="mb-5"><CurrentStreak streak={own?.streak_attuale ?? 0} /></div>}
      <span id="classifica-fantabet" className="block scroll-mt-24" aria-hidden="true" /><div className="grid items-start gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(290px,1fr)]">
        <section aria-label="Schedina FantaBet" className="min-w-0 space-y-3">
          {readOnlyRound && !preOpen && <PastRoundSummary bets={initial.bets} predictions={predictionByBet} played={Boolean(submission)} demo={demo} roundNumber={round.number} streak={demo ? round.number % 5 : own?.streak_attuale ?? 0} roundResult={initial.roundLeaderboard.find((row) => row.profile_id === initial.viewerId)} />}
          {readOnlyRound && !preOpen && <RoundTipsters rows={initial.roundLeaderboard} />}
          {initial.bets.map((bet) => <div key={bet.id} ref={(node) => { if (node) betRefs.current.set(bet.id, node); else betRefs.current.delete(bet.id); }}>{readOnlyRound ? <PastBetCard bet={bet} prediction={predictionByBet.get(bet.id)} /> : <BetCard bet={bet} prediction={predictionByBet.get(bet.id)} viewerId={initial.viewerId} writable={writable} submitted={confirmed} playConfirmed={confirmedBets.has(bet.id)} demo={demo} expanded={expanded.has(bet.id)} onToggle={() => setExpanded((current) => current.has(bet.id) ? new Set() : new Set([bet.id]))} onConfirmPlay={() => confirmPlay(bet.id)} onSaved={saved} />}</div>)}
          {!readOnlyRound && <SlipStatus hydrated={hydrated} completed={completed} confirmedCount={confirmedBets.size} required={round.requiredPredictions} writable={serverWindowOpen} confirmed={confirmed} needsReconfirmation={needsReconfirmation} deadlinePassed={deadlinePassed} pending={submissionPending} message={submissionMessage} onConfirm={confirm} onReopen={reopen} />}
        </section>
        <LeaderboardSidebar rows={initial.leaderboard} viewerId={initial.viewerId} own={own} onFull={() => setFullLeaderboard(true)} showRecords={true} demo={demo} />
      </div>
    </div>
    {fullLeaderboard && <FullLeaderboard rows={initial.leaderboard} viewerId={initial.viewerId} onClose={() => setFullLeaderboard(false)} />}
  </main>;
}

function BetCard({ bet, prediction, viewerId, writable, submitted, playConfirmed, demo, expanded, onToggle, onConfirmPlay, onSaved }: { bet: FantaBetBetView; prediction?: FantaBetPredictionRow; viewerId: string | null; writable: boolean; submitted: boolean; playConfirmed: boolean; demo: boolean; expanded: boolean; onToggle: () => void; onConfirmPlay: () => void; onSaved: (prediction: FantaBetPredictionRow) => void }) {
  const [pending, startTransition] = useTransition();
  const [feedback, setFeedback] = useState("");
  const [home, setHome] = useState(prediction?.exact_home ?? 0);
  const [away, setAway] = useState(prediction?.exact_away ?? 0);
  const complete = isCompletePrediction(bet.type, prediction);
  const controlsDisabled: boolean = Boolean(!writable || pending || submitted);
  const confirmPlayDisabled: boolean = Boolean(submitted || pending || (bet.type !== "RISULTATO_ESATTO" && !complete));
  const meta = bet.type === "FANTAPUNTEGGIO_1X2" ? ["FANTAPUNTEGGIO PIÙ ALTO", "Quale squadra farà il fantapunteggio maggiore?"] : bet.type === "UNDER_OVER_2_5" ? ["UNDER / OVER 2.5", "Quanti gol segneranno in totale?"] : bet.type === "RISULTATO_ESATTO" ? ["RISULTATO ESATTO", "Indovina il punteggio finale"] : ["1X2", "Pronostica l'esito della partita"];
  const accent = betTypeAccent(bet.type);
  function save(choice: FantaBetChoice, exactHome?: number, exactAway?: number, confirmAfterSave = false) {
    if (!viewerId || !writable || submitted) return; setFeedback("");
    if (demo) { onSaved({ id: bet.id, bet_id: bet.id, scelta: choice, exact_home: exactHome ?? null, exact_away: exactAway ?? null }); setFeedback("Salvato in demo"); if (confirmAfterSave) onConfirmPlay(); return; }
    startTransition(async () => { const result = await saveFantaBetPrediction({ betId: bet.id, choice, exactHome, exactAway }); setFeedback(result.message); if (result.ok && result.prediction) { onSaved(result.prediction); if (confirmAfterSave) onConfirmPlay(); } });
  }
  if (!expanded) return <CompactBetCard bet={bet} accent={accent} onClick={writable || submitted ? onToggle : undefined} confirmed={playConfirmed} topRight={`${bet.points} PT`} bottomRight={complete ? predictionLabel(bet.type, prediction) : "GIOCA"} />;
  return <article className={`min-w-0 rounded-2xl border border-l-4 bg-white p-3 shadow-[0_10px_30px_rgba(15,23,42,.06)] transition-[transform,box-shadow] motion-reduce:transition-none sm:p-5 sm:hover:-translate-y-0.5 sm:hover:shadow-[0_14px_34px_rgba(15,23,42,.10)] ${accent.border}`}>
    <button type="button" onClick={onToggle} aria-expanded={true} aria-label={`Richiudi ${meta[0]}`} className="flex w-full cursor-pointer items-start justify-between gap-3 text-left"><div><p className={`text-[11px] font-black uppercase tracking-wider ${accent.text}`}>{meta[0]}</p><p className="mt-0.5 text-xs font-semibold text-slate-500">{meta[1]}</p></div><span className="flex shrink-0 items-center gap-2"><span className={`${accent.badge} rounded-full px-2.5 py-1 text-[10px] font-black`}>{bet.points} PT</span><span aria-hidden="true" className="text-slate-400">⌃</span></span></button>
    <div className="mt-3">{(bet.type === "UNDER_OVER_2_5" || bet.type === "RISULTATO_ESATTO") && <TeamHeader bet={bet} />}
    {!viewerId ? <Link href="/account/accedi" className="block rounded-xl border border-blue-950 px-4 py-3 text-center text-sm font-black">Accedi per giocare</Link> : bet.type === "RISULTATO_ESATTO" ? <ExactScore home={home} away={away} disabled={controlsDisabled} onHome={setHome} onAway={setAway} /> : bet.type === "UNDER_OVER_2_5" ? <div className="grid grid-cols-2 gap-2">{predictionOptions(bet.type).map((option) => <ChoiceButton key={option.value} label={option.label} selected={prediction?.scelta === option.value} disabled={controlsDisabled} onClick={() => save(option.value)} />)}</div> : <VisualChoices bet={bet} prediction={prediction} disabled={controlsDisabled} onSave={save} fantasy={bet.type === "FANTAPUNTEGGIO_1X2"} />}
    </div><div aria-live="polite" className="mt-2 min-h-4 text-center text-[11px] font-bold text-slate-500">{pending ? "Salvataggio…" : feedback}</div>
    <LineupsDisclosure bet={bet} />
    <CombinedStatsPanel bet={bet} />
    {submitted ? <div role="status" className="mt-3 grid min-h-11 w-full place-items-center rounded-xl bg-emerald-100 text-xs font-black text-emerald-800">GIOCATA EFFETTUATA ✓</div> : <button type="button" disabled={confirmPlayDisabled} onClick={() => bet.type === "RISULTATO_ESATTO" ? save("ESATTO", home, away, true) : onConfirmPlay()} className="mt-3 min-h-11 w-full rounded-xl bg-emerald-600 text-xs font-black text-white transition-colors motion-reduce:transition-none disabled:cursor-not-allowed disabled:bg-slate-200 disabled:text-slate-500">CONFERMA GIOCATA</button>}
  </article>;
}

function LineupsDisclosure({ bet }: { bet: FantaBetBetView }) {
  if (!bet.homeLineup && !bet.awayLineup) return null;
  return <details className="mt-3 rounded-xl border border-sky-200 bg-sky-50/70"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between px-3 text-xs font-black uppercase text-sky-800">Vedi formazioni <span aria-hidden="true">＋</span></summary><div className="grid gap-3 border-t border-sky-200 p-3 sm:grid-cols-[1fr_auto_1fr]"><LineupTeam name={bet.home.name} lineup={bet.homeLineup} /><strong className="self-center text-center text-xs text-slate-400">VS</strong><LineupTeam name={bet.away.name} lineup={bet.awayLineup} /></div></details>;
}
function LineupTeam({ name, lineup }: { name: string; lineup: FantaBetBetView["homeLineup"] }) { return <section className="min-w-0 rounded-xl bg-white p-3"><h4 className="truncate text-sm font-black uppercase text-blue-950">{name}</h4>{lineup ? <><p className="mt-1 text-xs font-black text-sky-700">{lineup.formation ?? "Modulo non disponibile"}</p><ol className="mt-2 space-y-1">{lineup.players.map((player) => <li key={`${player.order}-${player.name}`} className="text-xs font-semibold text-slate-700"><span className="mr-1 text-slate-400">{player.order}.</span>{player.name}{player.captain ? " (C)" : player.viceCaptain ? " (VC)" : ""}</li>)}</ol></> : <p className="mt-2 text-xs font-semibold text-slate-500">Formazione non ancora disponibile</p>}</section>; }

function CompactBetCard({ bet, accent, topRight, bottomRight, confirmed = false, outcome = "neutral", historical = false, onClick }: { bet: FantaBetBetView; accent: ReturnType<typeof betTypeAccent>; topRight: ReactNode; bottomRight: ReactNode; confirmed?: boolean; outcome?: "neutral" | "correct" | "wrong"; historical?: boolean; onClick?: () => void }) {
  const outcomeTone = outcome === "correct" ? "border-emerald-300 bg-emerald-50 text-emerald-900 shadow-[inset_2px_0_0_#10b981]" : outcome === "wrong" ? "border-rose-300 bg-rose-50 text-rose-900 shadow-[inset_2px_0_0_#f43f5e]" : "border-slate-200 bg-slate-50 text-blue-950";
  const content = <><strong className={`m-1 grid min-w-0 place-items-center rounded-lg border border-current/15 px-1 text-center text-[10px] font-black uppercase shadow-[inset_0_1px_0_rgba(255,255,255,.55)] sm:text-[11px] ${accent.badge}`}>{shortType(bet.type)}</strong><span title={`${bet.home.name} vs ${bet.away.name}`} className="flex min-w-0 items-center gap-1 overflow-hidden px-1 py-2 text-[11px] font-black text-blue-950 sm:gap-1.5 sm:px-2 sm:text-[13px]"><span aria-hidden="true" className={`grid h-5 w-5 shrink-0 place-items-center rounded-full text-[10px] font-black ${confirmed ? "bg-emerald-100 text-emerald-700" : "bg-transparent text-transparent"}`}>{confirmed ? "✓" : ""}</span><Image src={bet.home.logo} alt="" width={24} height={24} unoptimized className="h-[22px] w-[22px] shrink-0 object-contain sm:h-6 sm:w-6" /><TeamNameMarquee name={bet.home.name} /><span className="shrink-0 text-[9px] font-bold text-slate-400 sm:text-[10px]">vs</span><Image src={bet.away.logo} alt="" width={24} height={24} unoptimized className="h-[22px] w-[22px] shrink-0 object-contain sm:h-6 sm:w-6" /><TeamNameMarquee name={bet.away.name} /></span><CompactBetOutcome top={topRight} bottom={bottomRight} historical={historical} tone={outcomeTone} /></>;
  const classes = `grid min-h-16 w-full grid-cols-[44px_minmax(0,1fr)_64px] overflow-hidden rounded-2xl border border-slate-200/70 border-l-4 bg-white text-left shadow-[0_5px_16px_rgba(15,23,42,.06)] transition-[transform,box-shadow] motion-reduce:transition-none sm:grid-cols-[52px_minmax(0,1fr)_72px] sm:hover:-translate-y-0.5 sm:hover:shadow-[0_8px_20px_rgba(15,23,42,.09)] ${accent.border}`;
  return onClick ? <button type="button" onClick={onClick} aria-expanded={false} className={classes}>{content}</button> : <article className={classes}>{content}</article>;
}

function CompactBetOutcome({ top, bottom, historical, tone }: { top: ReactNode; bottom: ReactNode; historical: boolean; tone: string }) { return <span className={`grid min-w-0 grid-rows-[1fr_2fr] border-l text-center ${tone}`}><strong className="grid min-w-0 place-items-center whitespace-nowrap px-1 text-[10px] tabular-nums sm:text-xs">{top}</strong><span className="grid min-w-0 place-items-center whitespace-nowrap border-t border-current/20 px-1 text-base font-black uppercase leading-none sm:text-lg">{bottom}</span><span className="sr-only">{historical ? "Risultato e pronostico" : "Punti e pronostico"}</span></span>; }

function TeamNameMarquee({ name }: { name: string }) { const containerRef = useRef<HTMLSpanElement>(null); const measureRef = useRef<HTMLSpanElement>(null); const [distance, setDistance] = useState(0); useEffect(() => { const container = containerRef.current; const measureText = measureRef.current; if (!container || !measureText) return; const motion = window.matchMedia("(prefers-reduced-motion: reduce)"); const measure = () => setDistance(motion.matches ? 0 : Math.max(0, Math.ceil(measureText.scrollWidth - container.clientWidth))); measure(); const observer = new ResizeObserver(measure); observer.observe(container); motion.addEventListener("change", measure); return () => { observer.disconnect(); motion.removeEventListener("change", measure); }; }, [name]); const style = distance > 0 ? ({ "--team-name-distance": `${distance}px` } as CSSProperties) : undefined; return <span ref={containerRef} title={name} aria-label={name} className="relative min-w-0 flex-1 overflow-hidden whitespace-nowrap"><span ref={measureRef} aria-hidden="true" className="pointer-events-none absolute invisible min-w-max">{name}</span>{distance > 0 ? <span style={style} className="fantabet-team-name-marquee block min-w-max">{name}</span> : <span className="block max-w-full truncate">{name}</span>}</span>; }

function TeamHeader({ bet }: { bet: FantaBetBetView }) { return <div className="my-4 grid grid-cols-[minmax(0,1fr)_auto_minmax(0,1fr)] items-start gap-1 text-center sm:gap-2"><TeamSummary team={bet.home} stats={bet.homeStats} recentResults /><span className="pt-4 text-[10px] font-black text-slate-400">VS</span><TeamSummary team={bet.away} stats={bet.awayStats} recentResults /></div>; }
function TeamSummary({ team, stats, recentResults = false }: { team: FantaBetTeam; stats: FantaBetStats; recentResults?: boolean }) { return <div className="min-w-0"><Image src={team.logo} alt={`Logo ${team.name}`} width={48} height={48} unoptimized className="mx-auto h-11 w-11 object-contain" /><p className="mt-1 truncate text-xs font-black uppercase">{team.name}</p><p className="mt-1 truncate text-[8px] font-bold text-slate-500 sm:text-[9px]">POS {stats.position ? `${stats.position}°` : "–"} · PT {stats.points ?? "–"} · FPT.TOT {stats.fantasyPointsTotal ?? "–"}</p>{recentResults ? <RecentResults stats={stats} /> : <Form form={stats.form} />}</div>; }
function Form({ form }: { form: string[] }) { return <div aria-label={`Ultime partite: ${form.join(", ") || "non disponibili"}`} className="mt-1 flex min-w-0 justify-center gap-0.5 sm:gap-1">{form.map((value, index) => <span key={`${value}-${index}`} className={`grid h-4 min-w-4 place-items-center rounded-full border px-0.5 text-[8px] font-black text-white shadow-[inset_0_1px_0_rgba(255,255,255,.28),0_1px_2px_rgba(15,23,42,.12)] sm:h-5 sm:min-w-5 sm:px-1 sm:text-[9px] ${value === "V" ? "border-emerald-500 bg-emerald-600" : value === "S" ? "border-rose-500 bg-rose-600" : value === "P" ? "border-slate-400 bg-slate-500" : "border-slate-300 bg-slate-400"}`}>{value}</span>)}</div>; }
function RecentResults({ stats }: { stats: FantaBetStats }) { return <div aria-label="Ultimi 3 risultati" className="mt-1 flex min-w-0 justify-center gap-1 overflow-hidden">{stats.details.slice(0, 3).map((match) => { const tone = match.goalsFor > match.goalsAgainst ? "border-emerald-200 bg-emerald-50 text-emerald-700" : match.goalsFor < match.goalsAgainst ? "border-rose-200 bg-rose-50 text-rose-700" : "border-slate-200 bg-slate-100 text-slate-600"; return <span key={match.matchday} className={`shrink-0 rounded-md border px-1 py-0.5 text-[8px] font-black ${tone}`}><span aria-label={match.home ? "Casa" : "Trasferta"}>{match.home ? "🏠" : "✈️"}</span> {match.goalsFor}-{match.goalsAgainst}</span>; })}</div>; }
function FantasyValues({ stats, opponent }: { stats: FantaBetStats; opponent: FantaBetStats }) { return <div aria-label="Ultimi 3 fantapunteggi" className="mt-1 flex min-w-0 justify-center gap-1 overflow-hidden">{stats.details.slice(0, 3).map((match, index) => { const value = match.fantasyPoints; const other = opponent.details[index]?.fantasyPoints; const comparison = value == null || other == null || value === other ? "tie" : value > other ? "higher" : "lower"; const tone = comparison === "higher" ? "border-emerald-300 bg-emerald-50 text-emerald-800" : comparison === "lower" ? "border-rose-300 bg-rose-50 text-rose-800" : "border-slate-300 bg-slate-100 text-slate-600"; return <span key={match.matchday} className={`shrink-0 rounded-md border px-1 py-0.5 text-[7px] font-black shadow-sm sm:text-[8px] ${tone}`}>{value ?? "–"}<span className="sr-only">{comparison === "higher" ? " maggiore" : comparison === "lower" ? " minore" : " pari"}</span></span>; })}</div>; }
function VisualChoices({ bet, prediction, disabled, onSave, fantasy }: { bet: FantaBetBetView; prediction?: FantaBetPredictionRow; disabled: boolean; onSave: (choice: FantaBetChoice) => void; fantasy: boolean }) { return <div className="grid grid-cols-3 items-stretch gap-1.5 sm:gap-2">{(["1", "X", "2"] as FantaBetChoice[]).map((choice) => { const team = choice === "1" ? bet.home : choice === "2" ? bet.away : null; const stats = choice === "1" ? bet.homeStats : bet.awayStats; const opponent = choice === "1" ? bet.awayStats : bet.homeStats; const selected = prediction?.scelta === choice; return <button key={choice} disabled={disabled} aria-pressed={selected} onClick={() => onSave(choice)} className={`min-h-36 min-w-0 overflow-hidden rounded-xl border p-1.5 text-center transition motion-reduce:transition-none focus:outline-none focus-visible:ring-2 focus-visible:ring-sky-300 disabled:opacity-50 sm:p-2 ${selected ? "border-sky-600 bg-sky-600 text-white shadow-[0_0_0_2px_rgba(14,165,233,.28)]" : `border-slate-200 ${fantasy ? "bg-sky-50" : "bg-slate-50"} hover:border-sky-400 focus:border-sky-500`}`}><strong className="block text-lg">{choice}</strong>{team ? <><Image src={team.logo} alt={`Logo ${team.name}`} width={38} height={38} unoptimized className="mx-auto h-9 w-9 object-contain" /><span className="mt-1 block truncate text-[9px] font-black uppercase sm:text-[10px]">{team.name}</span>{fantasy ? <span className="mt-1 block text-[8px] font-bold opacity-75 sm:text-[9px]">POS {stats.position ? `${stats.position}°` : "–"} · PT {stats.points ?? "–"} · FPT.TOT {stats.fantasyPointsTotal ?? "–"}</span> : <><span className="mt-1 grid grid-cols-2 place-items-center gap-x-1 text-[8px] font-bold leading-tight opacity-75 sm:hidden"><span>POS {stats.position ? `${stats.position}°` : "–"}</span><span>PT {stats.points ?? "–"}</span><span className="col-span-2 mt-0.5 text-center">FPT.TOT {stats.fantasyPointsTotal ?? "–"}</span></span><span className="mt-1 hidden text-[9px] font-bold opacity-75 sm:block">POS {stats.position ? `${stats.position}°` : "–"} · PT {stats.points ?? "–"} · FPT.TOT {stats.fantasyPointsTotal ?? "–"}</span></>}{fantasy ? <FantasyValues stats={stats} opponent={opponent} /> : <Form form={stats.form} />}</> : <span className="mt-8 block text-[10px] font-black uppercase">Pareggio</span>}</button>; })}</div>; }
function ChoiceButton({ label, selected, disabled, onClick }: { label: string; selected: boolean; disabled: boolean; onClick: () => void }) { return <button disabled={disabled} onClick={onClick} aria-pressed={selected} className={`min-h-14 rounded-xl border text-sm font-black transition motion-reduce:transition-none focus:outline-none focus-visible:ring-2 focus-visible:ring-sky-300 disabled:opacity-50 ${selected ? "border-sky-600 bg-sky-600 text-white shadow-[0_0_0_2px_rgba(14,165,233,.28)]" : "border-slate-200 bg-slate-50 hover:border-sky-400"}`}>{label}</button>; }
function ExactScore({ home, away, disabled, onHome, onAway }: { home: number; away: number; disabled: boolean; onHome: (value: number) => void; onAway: (value: number) => void }) { return <div aria-label="Risultato esatto selezionato" className="mx-auto flex w-fit items-center justify-center gap-1.5 rounded-2xl bg-slate-50 p-1 shadow-[inset_0_0_0_1px_rgba(148,163,184,.22)]"><Stepper label="Gol casa" value={home} disabled={disabled} onChange={onHome} /><span className="font-black text-slate-300">–</span><Stepper label="Gol ospite" value={away} disabled={disabled} onChange={onAway} /></div>; }
function Stepper({ label, value, disabled, onChange }: { label: string; value: number; disabled: boolean; onChange: (value: number) => void }) { return <div className="flex items-center overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200/60"><button type="button" aria-label={`Diminuisci ${label}`} disabled={Boolean(disabled || value === 0)} onClick={() => onChange(clampExactScore(value - 1))} className="h-12 w-10 bg-slate-100/80 text-xl font-black text-slate-600 outline-none transition-colors focus-visible:bg-sky-100 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-sky-300 disabled:opacity-30">−</button><label className="sr-only">{label}</label><input aria-label={label} inputMode="numeric" min={0} max={20} value={value} disabled={disabled} onChange={(event) => onChange(clampExactScore(Number(event.target.value)))} className="h-12 w-11 border-x border-slate-200/60 bg-white text-center text-xl font-black outline-none focus:bg-sky-50" /><button type="button" aria-label={`Aumenta ${label}`} disabled={Boolean(disabled || value === 20)} onClick={() => onChange(clampExactScore(value + 1))} className="h-12 w-10 bg-slate-100/80 text-xl font-black text-slate-600 outline-none transition-colors focus-visible:bg-sky-100 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-sky-300 disabled:opacity-30">+</button></div>; }
function CurrentStreak({ streak }: { streak: number }) { const state = currentStreakPresentation(streak); return <aside aria-label="Progresso Bonus Costanza" className="rounded-2xl border border-amber-200/80 bg-gradient-to-r from-amber-50 via-white to-sky-50 px-3 py-2.5 text-center shadow-[0_5px_16px_rgba(146,64,14,.07)]"><div className="mx-auto flex h-6 max-w-56 items-center justify-center gap-2">{Array.from({ length: 5 }, (_, index) => <i key={index} className={`grid h-5 place-items-center rounded-full border font-black not-italic shadow-sm ${index === 4 ? "w-9 text-[7px]" : "w-5 text-[6px]"} ${index < state.progress ? "border-amber-300 bg-amber-400 text-blue-950" : "border-slate-300 bg-white text-slate-400"}`}>{index === 4 && state.progress === 5 ? "+10" : ""}</i>)}</div><p className="mt-1 text-[9px] font-black uppercase tracking-wide text-blue-950 sm:text-[10px]">{state.message}</p></aside>; }
function CombinedStatsPanel({ bet }: { bet: FantaBetBetView }) { return <details className="min-w-0 rounded-xl border border-slate-100 bg-slate-50 p-2 text-xs sm:p-3"><summary className="cursor-pointer list-none font-black text-sky-800">STATISTICHE</summary><div className="mt-3 grid grid-cols-[minmax(0,1fr)_1px_minmax(0,1fr)] items-stretch gap-1 sm:gap-3"><DetailedTeamStats team={bet.home} stats={bet.homeStats} label="SQUADRA CASA" /><span aria-hidden="true" className="bg-gradient-to-b from-transparent via-slate-300 to-transparent" /><DetailedTeamStats team={bet.away} stats={bet.awayStats} label="SQUADRA OSPITE" /></div></details>; }
function DetailedTeamStats({ team, stats, label }: { team: FantaBetTeam; stats: FantaBetStats; label: string }) { return <section className="min-w-0 rounded-lg bg-white p-1.5 sm:rounded-xl sm:p-3"><p className="truncate text-[7px] font-black tracking-wide text-slate-400 sm:text-[9px] sm:tracking-wider">{label}</p><div className="flex min-w-0 items-center justify-between gap-1"><h3 className="truncate text-[9px] font-black uppercase sm:text-xs">{team.name}</h3><Image src={team.logo} alt={`Logo ${team.name}`} width={28} height={28} unoptimized className="h-5 w-5 shrink-0 object-contain sm:h-7 sm:w-7" /></div><dl className="mt-2 grid grid-cols-2 gap-x-1 gap-y-1 text-[8px] text-slate-600 sm:gap-x-2 sm:text-[10px]"><dt title="Posizione in campionato">POS</dt><dd className="text-right font-black">{stats.position ? `${stats.position}°` : "–"}</dd><dt title="Punti in campionato">PT</dt><dd className="text-right font-black">{stats.points ?? "–"}</dd><dt title="Fantapunti totali accumulati">FPT.TOT</dt><dd className="truncate text-right font-black">{stats.fantasyPointsTotal ?? "–"}</dd><dt title="Gol fatti">GF</dt><dd className="text-right font-black">{stats.goalsFor}</dd><dt title="Gol subiti">GS</dt><dd className="text-right font-black">{stats.goalsAgainst}</dd><dt title="Media fantapunti per partita">MEDIA FPT</dt><dd className="text-right font-black">{stats.averageFantasy ?? "–"}</dd></dl><p className="mt-2 truncate text-[7px] font-black uppercase text-slate-400 sm:mt-3 sm:text-[9px]">Ultime 5</p><div className="mt-1 space-y-1">{stats.details.map((match) => { const outcome = match.goalsFor > match.goalsAgainst ? "win" : match.goalsFor < match.goalsAgainst ? "loss" : "draw"; return <p key={match.matchday} className={`truncate text-[7px] font-bold sm:text-[10px] ${outcome === "win" ? "text-emerald-700" : outcome === "loss" ? "text-rose-700" : "text-slate-500"}`}><span aria-label={match.home ? "Casa" : "Trasferta"}>{match.home ? "🏠" : "✈️"}</span> G{match.matchday} · {match.goalsFor}-{match.goalsAgainst} · {match.fantasyPoints ?? "–"} FPT</p>; })}</div><Link href={`/societa/${team.slug}#rosa`} className="mt-2 inline-flex text-[7px] font-black text-sky-700 sm:mt-3 sm:text-[10px]">ROSA 2026/27</Link></section>; }

function SlipStatus({ hydrated, completed, confirmedCount, required, writable, confirmed, needsReconfirmation, deadlinePassed, pending, message, onConfirm, onReopen }: { hydrated: boolean; completed: number; confirmedCount: number; required: number; writable: boolean; confirmed: boolean; needsReconfirmation: boolean; deadlinePassed: boolean; pending: boolean; message: string; onConfirm: () => void; onReopen: () => void }) { const disabled = isSubmitButtonDisabled({ hydrated, completed, confirmed: confirmedCount, required, writable, pending }); const status = deadlinePassed ? "Schedina non confermata" : needsReconfirmation ? "Da confermare" : completed === required ? "Schedina pronta da confermare" : `${confirmedCount}/${required} giocate confermate`; if (confirmed) return <div className="space-y-2"><div className="flex min-h-14 items-center justify-between rounded-2xl border border-emerald-300 bg-emerald-50 px-4 shadow-lg"><strong className="text-emerald-800">SCHEDINA COMPILATA</strong><span className="text-xl font-black text-emerald-600">✓</span></div>{!deadlinePassed && <button disabled={Boolean(pending)} onClick={onReopen} className="min-h-12 w-full rounded-2xl border border-blue-950 bg-white text-xs font-black text-blue-950 disabled:opacity-40">MODIFICA SCHEDINA</button>}{message && <p aria-live="polite" className="text-center text-xs font-bold text-slate-600">{message}</p>}</div>; return <div className="sticky bottom-3 z-20 rounded-2xl border border-slate-200 bg-white p-4 text-center shadow-xl lg:static"><strong>{status}</strong>{completed !== confirmedCount && <p className="mt-1 text-[11px] font-bold text-slate-500">{completed}/{required} pronostici salvati · {confirmedCount}/{required} giocate confermate</p>}<button disabled={disabled} onClick={onConfirm} className="mt-2 block min-h-12 w-full rounded-xl bg-blue-950 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-35">CONFERMA SCHEDINA</button>{message && <p aria-live="polite" className="mt-2 text-xs font-bold text-slate-600">{message}</p>}</div>; }
function Countdown({ deadline, now }: { deadline: string; now: number }) { const units = countdownParts(deadline, now); return <div className="w-full text-center sm:w-auto sm:text-right"><p className="mb-1 text-[9px] font-black uppercase tracking-widest text-slate-500">Deadline</p><div className="grid w-full grid-cols-4 gap-1 sm:w-auto">{units.map(([label, number]) => <div key={label} className="rounded-xl bg-blue-950 px-1 py-2 text-center text-white sm:min-w-14 sm:px-2"><strong className="block text-lg tabular-nums">{String(number).padStart(2, "0")}</strong><span className="text-[7px] font-black tracking-wide">{label}</span></div>)}</div></div>; }

function RoundNavigation({ rounds, previous, current, next, demo, currentId, selectedId }: { rounds: FantaBetPageData["availableRounds"]; previous: FantaBetPageData["availableRounds"][number] | null; current: number; next: FantaBetPageData["availableRounds"][number] | null; demo: boolean; currentId: number | null; selectedId: number }) { const selectedOptionRef = useRef<HTMLAnchorElement>(null); const href = (id: number) => `/fantabet?round=${id}${demo ? "&demo=1" : ""}`; const dot = <i aria-label="Giornata attuale" title="Giornata attuale" className="h-2 w-2 shrink-0 rounded-full bg-emerald-500 shadow-[0_0_7px_rgba(16,185,129,.75)]" />; return <nav aria-label="Navigazione giornate FantaBet" className="relative mx-auto mb-5 flex h-11 w-fit items-center rounded-xl border border-slate-200/80 bg-white text-xs font-black shadow-sm">{previous ? <Link href={href(previous.id)} aria-label="Giornata precedente" className="grid h-11 w-10 place-items-center rounded-l-xl text-xl text-blue-950 hover:bg-slate-50">‹</Link> : <button type="button" disabled={true} aria-label="Giornata precedente" className="h-11 w-10 rounded-l-xl text-xl text-blue-950 disabled:opacity-30">‹</button>}<details onToggle={(event) => { if (event.currentTarget.open) window.requestAnimationFrame(() => selectedOptionRef.current?.scrollIntoView({ block: "center", behavior: "auto" })); }} className="group relative h-11 border-x border-slate-200/80"><summary className="flex h-11 min-w-32 cursor-pointer list-none items-center justify-center gap-2 px-3 uppercase text-blue-950">{selectedId === currentId && dot}Giornata {current}</summary><div role="listbox" aria-label="Giornate disponibili" className="absolute left-1/2 top-[calc(100%+.35rem)] z-50 max-h-64 min-w-40 -translate-x-1/2 overflow-y-auto rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl">{rounds.map((round) => <Link ref={round.id === selectedId ? selectedOptionRef : undefined} key={round.id} href={href(round.id)} role="option" aria-selected={round.id === selectedId} className={`flex min-h-10 items-center gap-2 rounded-lg px-3 text-xs font-black ${round.id === selectedId ? "bg-sky-50 text-blue-950" : "text-slate-600 hover:bg-slate-50"}`}>{round.id === currentId ? dot : <i aria-hidden="true" className="h-2 w-2" />}Giornata {round.number}</Link>)}</div></details>{next ? <Link href={href(next.id)} aria-label="Giornata successiva" className="grid h-11 w-10 place-items-center rounded-r-xl text-xl text-blue-950 hover:bg-slate-50">›</Link> : <button type="button" disabled={true} aria-label="Giornata successiva" className="h-11 w-10 rounded-r-xl text-xl text-blue-950 disabled:opacity-30">›</button>}</nav>; }

function PastBetCard({ bet, prediction }: { bet: FantaBetBetView; prediction?: FantaBetPredictionRow }) { const score = prediction ? scorePlay(bet.type, bet.points, { choice: prediction.scelta as FantaBetChoice, exactHome: prediction.exact_home, exactAway: prediction.exact_away }, bet.result) : null; const result = bet.type === "FANTAPUNTEGGIO_1X2" ? `${bet.result.homeFantasyPoints ?? "–"} - ${bet.result.awayFantasyPoints ?? "–"}` : realResult(bet); const outcome = !score?.evaluable ? "neutral" : score.correct ? "correct" : "wrong"; return <div aria-label={`${shortType(bet.type)}: ${bet.home.name} contro ${bet.away.name}, risultato ${result}, scelta ${predictionLabel(bet.type, prediction)}`}><CompactBetCard bet={bet} accent={betTypeAccent(bet.type)} outcome={outcome} historical={true} topRight={result} bottomRight={predictionLabel(bet.type, prediction)} /></div>; }
function ConsistencyProgress({ streak, bonus }: { streak: number; bonus: number }) { const progress = bonus > 0 ? 5 : consistencyBlockProgress(streak); return <div className="grid min-h-14 content-center border-x border-white/20 px-1 text-center sm:px-2"><p className="text-[7px] font-black uppercase leading-none tracking-wide text-white/70 sm:text-[8px]">Bonus costanza</p><div aria-label={`${progress} giornate su 5 verso il bonus costanza`} className="relative mt-2 flex h-5 items-center justify-center gap-1 sm:h-6 sm:gap-2"><span aria-hidden="true" className="absolute left-2 right-4 top-1/2 h-px -translate-y-1/2 bg-white/25 sm:left-3 sm:right-5" />{Array.from({ length: 5 }, (_, index) => <i key={index} className={`relative z-10 grid h-5 place-items-center rounded-full border font-black not-italic shadow-sm sm:h-6 ${index === 4 ? "w-8 text-[7px] sm:w-10 sm:text-[8px]" : "w-5 text-[6px] sm:w-6 sm:text-[7px]"} ${index < progress ? "border-amber-200 bg-gradient-to-b from-amber-200 to-amber-400 text-blue-950 shadow-amber-300/30" : "border-white/60 bg-blue-900 text-white shadow-black/10"}`}>{index === 4 ? "+10" : ""}</i>)}</div></div>; }
function PastRoundSummary({ bets, predictions, played, demo, roundNumber, streak, roundResult }: { bets: FantaBetBetView[]; predictions: Map<number, FantaBetPredictionRow>; played: boolean; demo: boolean; roundNumber: number; streak: number; roundResult?: FantaBetPageData["roundLeaderboard"][number] }) { const scores = bets.map((bet) => { const prediction = predictions.get(bet.id); return prediction ? scorePlay(bet.type, bet.points, { choice: prediction.scelta as FantaBetChoice, exactHome: prediction.exact_home, exactAway: prediction.exact_away }, bet.result) : null; }); const evaluable = played && scores.every((score) => score?.evaluable); const derivedCorrect = scores.filter((score) => score?.correct).length; const correct = roundResult?.pronostici_corretti ?? derivedCorrect; const base = scores.reduce((sum, score) => sum + (score?.points ?? 0), 0); const perfect = evaluable && correct === bets.length && (roundResult?.schedina_perfetta ?? scores.every((score) => score?.correct)); const derivedPredictionPoints = perfect ? base * 2 : base; const predictionPoints = !demo && roundResult ? roundResult.punti_pronostici : derivedPredictionPoints; const consistencyBonus = demo && roundNumber % 5 === 0 ? 10 : roundResult?.punti_bonus_costanza ?? 0; const total = predictionPoints + consistencyBonus; return <section className="relative rounded-2xl border border-blue-300 bg-gradient-to-r from-blue-950 to-blue-800 p-4 text-white shadow-lg"><div className="flex min-h-4 items-start justify-between gap-3"><p className="text-[9px] font-black uppercase tracking-[.2em] text-sky-200">Punti effettuati</p>{perfect && <p className="shrink-0 text-[9px] font-black uppercase tracking-wide text-amber-300">★ Schedina perfetta</p>}</div>{!played ? <strong className="mt-4 block text-center text-sm uppercase">Pronostici non effettuati per questa giornata</strong> : evaluable ? <><strong className="mt-1 block text-center text-4xl font-black">{total} PT</strong><div className="mt-3 grid grid-cols-[minmax(0,1fr)_minmax(0,2fr)_minmax(0,1fr)] items-stretch gap-2 rounded-xl bg-white/10 p-2 text-center"><div className="grid min-h-14 place-items-center"><strong aria-label={`${correct} pronostici corretti su ${bets.length}`} className="text-2xl">{correct}/{bets.length}</strong></div><ConsistencyProgress streak={streak} bonus={consistencyBonus} /><div title={perfect ? "Moltiplicatore schedina perfetta ottenuto" : "Moltiplicatore schedina perfetta non ottenuto"} aria-label={perfect ? "Moltiplicatore schedina perfetta ottenuto" : "Moltiplicatore schedina perfetta non ottenuto"} className={`grid min-h-14 place-items-center rounded-lg border ${perfect ? "border-emerald-300 bg-emerald-500/30 text-emerald-200" : "border-rose-300 bg-rose-500/30 text-rose-200"}`}><strong className="text-2xl">×2</strong></div></div></> : <strong className="mt-4 block text-center text-sm">Valutazione della giornata in corso</strong>}</section>; }

function RoundTipsters({ rows }: { rows: FantaBetPageData["roundLeaderboard"] }) { const top = rows.slice(0, 3); if (top.length === 0) return null; const podium = ["border-amber-400 bg-amber-200/90 shadow-[0_5px_14px_rgba(217,119,6,.20)]", "border-slate-400 bg-slate-200/90", "border-orange-400 bg-orange-200/80"]; const rankTone = ["text-amber-900", "text-slate-700", "text-orange-900"]; return <section className="rounded-2xl border border-amber-200 bg-amber-50/70 p-3"><h2 className="text-[10px] font-black uppercase tracking-wider text-amber-900">Tipster di giornata</h2><div className="mt-2 grid grid-cols-3 gap-1.5">{top.map((row, index) => <Link key={row.profile_id} href={`/user/${encodeURIComponent(row.username)}`} className={`min-w-0 rounded-lg border px-2 py-2 text-center shadow-sm ${podium[index]}`}><strong className={`${index === 0 ? "text-sm" : "text-xs"} ${rankTone[index]}`}>{index + 1}°</strong><span className="mt-0.5 flex min-w-0 items-center justify-center gap-1"><span className="truncate text-[9px] font-black text-blue-950">{row.username}</span><OfficialAccountBadge societaId={row.societa_id} className="!h-3.5 !w-3.5 shrink-0" /></span><span className="block text-[9px] font-black text-blue-950">{row.punti_totali} PT</span></Link>)}</div></section>; }

function LeaderboardSidebar({ rows, viewerId, onFull, showRecords, demo }: { rows: FantaBetLeaderboardRow[]; viewerId: string | null; own?: FantaBetLeaderboardRow; onFull: () => void; showRecords: boolean; demo: boolean }) { const [filter, setFilter] = useState<LeaderboardFilter>("global"); const filtered = filterLeaderboard(rows, filter); const top = filtered.slice(0, 15); const positions = new Map(filtered.map((row, index) => [row.profile_id, filter === "global" ? row.posizione : index + 1])); const filteredOwn = filtered.find((row) => row.profile_id === viewerId); return <aside className="min-w-0 space-y-4 lg:sticky lg:top-24"><section className="rounded-2xl border border-slate-200 bg-gradient-to-b from-white to-slate-50 p-4 shadow-[0_14px_35px_rgba(15,23,42,.08)]"><div className="mb-3 flex justify-between"><h2 className="font-black uppercase">Classifica</h2><span className="text-[10px] font-bold text-slate-400">TOP 15</span></div><LeaderboardFilters value={filter} onChange={setFilter} /><LeaderboardRows rows={top} viewerId={viewerId} filter={filter} positions={positions} />{filteredOwn && !top.some((row) => row.profile_id === filteredOwn.profile_id) && <div className="mt-3 border-t border-dashed pt-3"><p className="mb-1 text-[10px] font-black uppercase text-slate-400">La tua posizione</p><LeaderboardRows rows={[filteredOwn]} viewerId={viewerId} filter={filter} positions={positions} /></div>}<button onClick={onFull} className="mt-4 w-full rounded-xl bg-blue-950 px-4 py-3 text-xs font-black text-white">Classifica completa</button></section>{showRecords && <SeasonRecords rows={rows} demo={demo} />}</aside>; }
function LeaderboardFilters({ value, onChange }: { value: LeaderboardFilter; onChange: (value: LeaderboardFilter) => void }) { const filters: Array<[LeaderboardFilter, string]> = [["global", "GLOBALE"], ["community", "COMMUNITY"], ["official", "VERIFICATI"]]; return <div className="mb-3"><div className="grid grid-cols-3 rounded-xl bg-slate-100 p-1">{filters.map(([id, label]) => <button key={id} onClick={() => onChange(id)} aria-pressed={value === id} className={`rounded-lg px-1 py-2 text-[9px] font-black sm:text-[10px] ${value === id ? "bg-white shadow" : ""}`}>{label}</button>)}</div>{value === "community" && <p className="mt-2 rounded-lg border border-emerald-200 bg-emerald-50 px-2 py-1.5 text-center text-[8px] font-black uppercase tracking-wider text-emerald-800">Top 10 · Qualificazione</p>}</div>; }
function LeaderboardRows({ rows, viewerId, filter = "global", positions }: { rows: FantaBetLeaderboardRow[]; viewerId: string | null; filter?: LeaderboardFilter; positions?: ReadonlyMap<string, number> }) { return <div className="space-y-1"><div className="grid grid-cols-[30px_minmax(0,1fr)_22px_22px_36px] gap-0.5 px-1.5 text-[8px] font-black uppercase text-slate-400 sm:grid-cols-[32px_minmax(0,1fr)_28px_24px_38px] sm:gap-1 sm:px-2"><span aria-label="Posizione" /><span>Username</span><span aria-label="Squadra" /><span title="Giornate giocate" aria-label="Giornate giocate" className="text-center">G</span><span className="text-right">PT</span></div>{rows.map((row) => { const rank = positions?.get(row.profile_id) ?? row.posizione; const tone = filter === "community" && rank <= 10 ? "border-emerald-400 bg-emerald-100/90 shadow-[inset_3px_0_0_#059669]" : rank === 1 ? "border-amber-400 bg-amber-100 shadow-[inset_3px_0_0_#d97706]" : filter === "global" && rank === 2 ? "border-slate-300 bg-slate-100" : filter === "global" && rank === 3 ? "border-orange-300 bg-orange-50" : row.profile_id === viewerId ? "border-sky-300 bg-sky-100" : "border-transparent bg-slate-50"; return <div key={row.profile_id}><div data-leaderboard-team-grid className={`grid min-w-0 grid-cols-[30px_minmax(0,1fr)_22px_22px_36px] items-center gap-0.5 rounded-lg border px-1.5 py-2 text-[11px] sm:grid-cols-[32px_minmax(0,1fr)_28px_24px_38px] sm:gap-1 sm:px-2 sm:text-xs ${tone}`}><strong className={`w-7 text-center tabular-nums sm:w-8 ${rank === 1 && filter !== "community" ? "text-amber-800" : filter === "community" && rank <= 10 ? "text-emerald-900" : "text-blue-950"}`}>{rank}</strong><Link href={`/user/${encodeURIComponent(row.username)}`} className="flex min-w-0 items-center gap-1 text-blue-950 hover:underline"><span className="truncate font-black tracking-[.01em]">{row.username}</span><OfficialAccountBadge societaId={row.societa_id} className="!h-4 !w-4 shrink-0" /></Link><span className="grid h-5 w-5 place-items-center justify-self-center sm:h-6 sm:w-6">{row.team_logo && row.team_name ? <Image src={row.team_logo} alt={`Logo ${row.team_name}`} title={row.team_name} width={24} height={24} className="h-5 w-5 object-contain sm:h-6 sm:w-6" /> : null}</span><span title="Giornate giocate" aria-label={`${row.giornate_giocate} giornate giocate`} className="text-center font-bold text-slate-600">{row.giornate_giocate}</span><strong className="text-right text-blue-950">{row.punti_totali}</strong></div>{filter === "community" && rank === 10 && <div className="my-2 flex items-center gap-2 text-[8px] font-black uppercase tracking-wider text-emerald-800"><span className="h-px flex-1 bg-emerald-500" />Zona qualificazione · Top 10<span className="h-px flex-1 bg-emerald-500" /></div>}</div>; })}</div>; }
function SeasonRecords({ rows, demo }: { rows: FantaBetLeaderboardRow[]; demo: boolean }) { if (!demo || rows.length === 0) return null; const mostPerfect = [...rows].sort((a, b) => b.schedine_perfette - a.schedine_perfette)[0]; const records = [{ label: "LA SBANCATA", username: rows[0].username, value: "38", unit: "PT", note: "Record in una giornata" }, { label: "L’IMPECCABILE", username: mostPerfect.username, value: String(mostPerfect.schedine_perfette), unit: "SCHEDINE PERFETTE", note: "En plein stagionali" }]; return <section aria-label="I Tipster Memorabili" className="rounded-2xl border border-amber-400/80 bg-gradient-to-br from-blue-950 via-blue-900 to-blue-800 p-3 text-white shadow-[0_14px_34px_rgba(15,23,42,.22)] sm:p-4"><h2 className="text-sm font-black uppercase tracking-[.16em] text-amber-200">I Tipster Memorabili</h2><div className="mt-3 grid grid-cols-2 gap-2">{records.map((record) => <article key={record.label} className="min-w-0 rounded-xl border border-amber-300/60 bg-white/10 p-2 text-center shadow-[inset_0_1px_0_rgba(255,255,255,.16),0_4px_12px_rgba(15,23,42,.16)] sm:p-3"><p className="truncate text-[8px] font-black tracking-tight text-amber-200 sm:text-[11px] sm:tracking-wider">{record.label}</p><strong className="mt-1 block truncate text-[10px] text-white sm:text-sm">{record.username}</strong><strong className="mt-1 block text-2xl leading-none text-white sm:mt-2 sm:text-3xl">{record.value}</strong><span className="mt-1 block truncate text-[7px] font-black uppercase text-sky-100 sm:text-[8px] sm:tracking-wide">{record.unit}</span><span className="mt-1 hidden text-[7px] font-semibold text-slate-300 sm:block">{record.note}</span></article>)}</div></section>; }
function FullLeaderboard({ rows, viewerId, onClose }: { rows: FantaBetLeaderboardRow[]; viewerId: string | null; onClose: () => void }) { const [query, setQuery] = useState(""); const [filter, setFilter] = useState<LeaderboardFilter>("global"); const filtered = filterLeaderboard(rows, filter); const positions = new Map(filtered.map((row, index) => [row.profile_id, filter === "global" ? row.posizione : index + 1])); const visible = searchLeaderboard(filtered, query); return <div role="dialog" aria-modal="true" aria-label="Classifica completa FantaBet" className="fixed inset-0 z-[120] bg-blue-950/55 p-3 backdrop-blur-sm"><div className="mx-auto flex max-h-full max-w-3xl flex-col rounded-2xl bg-white p-4 pr-2"><div className="flex justify-between pr-2"><h2 className="text-xl font-black">Classifica completa</h2><button onClick={onClose} aria-label="Chiudi" className="h-10 w-10 rounded-full bg-slate-100 font-black">×</button></div><div className="pr-2"><LeaderboardFilters value={filter} onChange={setFilter} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Cerca username" className="mb-3 h-11 w-full rounded-xl border px-3" /></div><div className="overflow-y-auto pr-3"><LeaderboardRows rows={visible} viewerId={viewerId} filter={filter} positions={positions} /></div></div></div>; }
function EmptyFantaBet({ leaderboard }: { leaderboard: FantaBetLeaderboardRow[] }) { return <main className="min-h-[70vh] bg-slate-50 px-4 py-16 text-center text-blue-950"><p className="section-eyebrow">Pronostica e sfida gli altri</p><h1 className="font-onder-title mt-2.5 text-5xl uppercase">Il FantaBet</h1><p className="mt-5 text-lg font-black">Nuova schedina in arrivo</p>{leaderboard.length > 0 && <div className="mx-auto mt-8 max-w-sm rounded-2xl bg-white p-4 text-left"><LeaderboardRows rows={leaderboard.slice(0, 15)} viewerId={null} /></div>}</main>; }
function shortType(type: FantaBetBetView["type"]) { return type === "UNDER_OVER_2_5" ? "U/O 2.5" : type === "RISULTATO_ESATTO" ? "RIS. ES." : type === "FANTAPUNTEGGIO_1X2" ? "FANTA PT" : "1X2"; }
function betTypeAccent(type: FantaBetBetView["type"]) { if (type === "UNDER_OVER_2_5") return { border: "border-l-amber-400", text: "text-amber-700", badge: "bg-amber-100 text-amber-900" }; if (type === "RISULTATO_ESATTO") return { border: "border-l-indigo-400", text: "text-indigo-700", badge: "bg-indigo-100 text-indigo-900" }; if (type === "FANTAPUNTEGGIO_1X2") return { border: "border-l-teal-400", text: "text-teal-700", badge: "bg-teal-100 text-teal-900" }; return { border: "border-l-sky-400", text: "text-sky-700", badge: "bg-sky-100 text-sky-900" }; }
function predictionLabel(type: FantaBetBetView["type"], prediction?: FantaBetPredictionRow) { if (!prediction) return "–"; if (type === "UNDER_OVER_2_5") return prediction.scelta === "UNDER" ? "U2.5" : "O2.5"; if (type === "RISULTATO_ESATTO") return `${prediction.exact_home ?? 0}-${prediction.exact_away ?? 0}`; return prediction.scelta; }
function realResult(bet: FantaBetBetView) { return bet.result.homeGoals === null || bet.result.awayGoals === null ? "–" : `${bet.result.homeGoals}-${bet.result.awayGoals}`; }
function emptySubscribe() { return () => undefined; }
