"use client";
import Image from "next/image";
import Link from "next/link";
import { useMemo, useState } from "react";
import AutoScrollName from "./ranking/AutoScrollName";
import OfficialAccountBadge from "./account/OfficialAccountBadge";
import DeadlineCountdown from "./fantabet/DeadlineCountdown";
import { GlobalCards } from "./campionati-live-preview/live-client";
import { calculateGlobalMatchdayStats, calculateSeasonStats, getLeagueRules, standingsAt } from "./campionati-live-preview/logic";
import type { LeagueData, LeagueId, Match, StandingRow, Team } from "./campionati-live-preview/types";
import { coppaStandingsForRange, isCalculatedCoppaMatch, qualificationSeparators } from "./coppe/coppa-fanta-fixture";
import type { HomeLiveData } from "@/lib/home/data.server";
import { fantaBetHomeState, isCalculatedHomeMatch, selectHomeMatchState } from "@/lib/home/logic";

const cta="inline-flex min-h-11 items-center justify-center rounded-full bg-blue-950 px-5 text-center text-[10px] font-black uppercase tracking-[.13em] text-white shadow-lg transition hover:bg-blue-800";
const assets={champions:"/icon/competizioni/champions_league_logo.png",europa:"/icon/competizioni/europa_league_logo.png",conference:"/icon/competizioni/conference_league_logo.png",promotion:"/icon/competizioni/scatto_promozione_logo.png"};
function Heading({eyebrow,title}:{eyebrow:string;title:string}){return <header className="mb-5 sm:mb-8"><p className="section-eyebrow">{eyebrow}</p><h2 className="font-onder-title mt-2 text-3xl uppercase leading-none text-blue-950 sm:text-5xl">{title}</h2></header>}
function latest(league:LeagueData){return Math.max(0,...league.matches.filter(isCalculatedHomeMatch).map(m=>m.matchday))}
function Move({value}:{value:number}){return <span className={`absolute right-0 text-[9px] font-black ${value>0?"text-emerald-600":value<0?"text-rose-600":"text-slate-400"}`}>{value>0?`↑${value}`:value<0?`↓${Math.abs(value)}`:"–"}</span>}
function Destination({row,leagueId}:{row:StandingRow;leagueId:LeagueId}){const item=row.position<=8?{icon:assets.champions,label:"Champions League"}:row.position<=14?{icon:assets.europa,label:"Europa League"}:{icon:assets.conference,label:"Conference League"};return <span className="flex justify-center gap-1"><Image src={item.icon} alt={item.label} width={17} height={17}/>{getLeagueRules(leagueId,row.position).scattoPromozione&&<Image src={assets.promotion} alt="Scatto Promozione" width={17} height={17}/>}</span>}

export default function HomeLiveSections({data}:{data:HomeLiveData|null}){if(!data)return null;const leagues=data.championships?.leagues.filter(l=>l.found)??[];const own=leagues.find(l=>l.teams.some(t=>t.id===data.viewer.teamId));return <>{data.viewer.id?<Personal data={data} leagues={leagues}/>:<GuestInvite/>}<Fanta data={data}/><Highlights leagues={leagues}/><Championship leagues={leagues} initial={own?.id??leagues[0]?.id??"serie-a"}/><Cup data={data}/></>}

function GuestInvite(){return <section className="mx-auto max-w-7xl px-4 pb-7 pt-2 sm:px-6 sm:pb-12"><div className="relative overflow-hidden rounded-[1.8rem] bg-blue-950 p-6 text-white shadow-xl sm:p-9"><span className="absolute -right-12 -top-16 h-44 w-44 rounded-full bg-sky-400/15 blur-3xl"/><p className="relative text-[9px] font-black uppercase tracking-[.22em] text-amber-300">Entra nel Fanta a 20</p><h2 className="relative mt-2 text-2xl font-black uppercase sm:text-4xl">Vivi il gioco da protagonista</h2><p className="relative mt-3 max-w-xl text-sm font-semibold text-white/60">Accedi o registrati per seguire la tua società.</p><div className="relative mx-auto mt-6 flex w-full max-w-md justify-center gap-3"><Link href="/account/accedi?returnTo=%2F" className="inline-flex min-h-12 flex-1 items-center justify-center rounded-full bg-amber-400 px-5 text-[11px] font-black uppercase text-blue-950 shadow-lg">Accedi</Link><Link href="/account/registrati" className="inline-flex min-h-12 flex-1 items-center justify-center rounded-full border border-white/25 px-5 text-[11px] font-black uppercase shadow-lg">Registrati</Link></div></div></section>}

function Personal({data,leagues}:{data:HomeLiveData;leagues:LeagueData[]}){const {league,team,last,next}=selectHomeMatchState(leagues,data.viewer.teamId);if(!league||!team)return null;const day=latest(league),row=day?standingsAt(league.teams,league.matches,day).find(r=>r.id===team.id):null;return <section className="mx-auto max-w-7xl px-4 pb-7 pt-2 sm:px-6 sm:pb-12"><div className="rounded-[1.8rem] bg-blue-950 p-4 text-white shadow-xl sm:p-7"><div className="grid gap-4 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><Link href={`/societa/${team.slug}`} className="group flex min-w-0 items-center gap-4"><Image src={team.logo} alt="" width={104} height={104} className="h-20 w-20 shrink-0 object-contain sm:h-28 sm:w-28"/><div className="min-w-0"><p className="text-[9px] font-black uppercase tracking-[.2em] text-sky-300">{data.viewer.relation==="official"?"La tua società":"La squadra che tifi"}</p><h2 className="mt-2 text-xl font-black uppercase sm:text-3xl"><AutoScrollName name={team.name}/></h2><p className="mt-1 text-[10px] font-bold uppercase text-white/50">{league.name}</p></div></Link><div className="grid gap-2 sm:grid-cols-2">{last&&<MatchBox match={last} title={`Ultima partita · Giornata ${last.matchday}`} result/>}{next&&<MatchBox match={next} title={`Prossima partita · Giornata ${next.matchday}`}/>} {!last&&!next&&<p className="rounded-xl bg-white/[.07] p-4 text-sm font-semibold text-white/60 sm:col-span-2">Calendario in preparazione.</p>}</div></div><div className="mt-4 border-t border-white/10 pt-4">{row&&row.played>0?<div className="grid grid-cols-3 text-center">{[["Posizione",`${row.position}°`],["PT",row.points],["PT TOT",row.fantasyPoints.toFixed(1)]].map(([label,value])=><div key={label}><strong className="block text-xl font-black">{value}</strong><span className="text-[8px] font-black uppercase text-white/45">{label}</span></div>)}</div>:<p className="text-center text-xs font-bold text-white/60">Classifica disponibile dalla prima giornata</p>}</div></div></section>}
function MatchBox({match,title,result=false}:{match:Match;title:string;result?:boolean}){return <article className="rounded-[1.2rem] border border-white/10 bg-white/[.07] p-3"><p className="mb-2 text-center text-[8px] font-black uppercase text-white/45">{title}</p><div className="grid grid-cols-[minmax(0,1fr)_54px_minmax(0,1fr)] items-center gap-1"><TeamMini team={match.home}/><b className="text-center">{result?`${match.homeGoals} - ${match.awayGoals}`:"VS"}</b><TeamMini team={match.away} reverse/></div></article>}
function TeamMini({team,reverse=false}:{team:Team;reverse?:boolean}){return <Link href={`/societa/${team.slug}`} className={`flex min-w-0 items-center gap-1 ${reverse?"flex-row-reverse text-right":""}`}><Image src={team.logo} alt="" width={32} height={32} className="h-8 w-8 shrink-0 object-contain"/><span className="min-w-0 flex-1 text-[9px] font-black uppercase"><AutoScrollName name={team.name}/></span></Link>}

function Fanta({data}:{data:HomeLiveData}){const round=data.fantabet.round,state=fantaBetHomeState(round,data.fantabet.submitted,data.viewer.id,data.serverNow);return <section className="bg-white/30 py-7 sm:py-10"><div className="mx-auto max-w-7xl px-4 sm:px-6"><Heading eyebrow="Pronostica e sfida gli altri" title="Il FantaBet"/><div className="grid gap-4 lg:grid-cols-[1.05fr_.95fr]"><article className="relative overflow-hidden rounded-[1.5rem] bg-[linear-gradient(145deg,#10264f,#071f45)] p-5 text-white shadow-xl"><span className="absolute -right-14 -top-14 h-40 w-40 rounded-full bg-sky-400/15 blur-3xl"/><h3 className="relative text-xl font-black uppercase">Gioca la tua schedina</h3>{round&&<div className="relative mt-4"><DeadlineCountdown deadline={round.deadlineAt} initialNow={new Date(data.serverNow).getTime()}/></div>}<Link href={state.href} className="relative mt-4 inline-flex min-h-12 w-full items-center justify-center rounded-full bg-amber-400 px-5 text-[10px] font-black uppercase text-blue-950 shadow-lg">Vai alla schedina</Link></article><article id="top-tipster-home" className="rounded-[1.5rem] bg-white p-4 shadow-[0_14px_35px_-28px_rgba(15,23,42,.4)]"><p className="text-[10px] font-black uppercase tracking-[.2em] text-sky-700">Top Tipster</p>{data.fantabet.leaderboard.length?<div className="mt-2 space-y-1">{data.fantabet.leaderboard.map(r=><div key={r.profile_id} className={`grid min-h-10 grid-cols-[28px_minmax(0,1fr)_26px_40px] items-center gap-1 rounded-lg border px-2 ${r.posizione===1?"border-amber-300 bg-amber-50":"border-transparent bg-slate-50"}`}><b className="text-center text-xs text-blue-950">{r.posizione}</b><Link href={`/user/${encodeURIComponent(r.username)}`} className="flex min-w-0 items-center gap-1 text-xs font-black text-blue-950"><AutoScrollName name={r.username}/><OfficialAccountBadge societaId={r.societa_id} className="!h-4 !w-4 shrink-0"/></Link>{r.team_logo?<Image src={r.team_logo} alt="" width={24} height={24} className="h-6 w-6 object-contain"/>:<span/>}<b className="text-right text-xs text-blue-950">{r.punti_totali}</b></div>)}</div>:<p className="mt-4 text-sm font-semibold text-slate-500">La corsa al vertice inizierà con la prima giornata.</p>}<Link href="/fantabet#classifica-fantabet" className="mt-4 inline-flex text-[9px] font-black uppercase tracking-wider text-blue-950">Esplora tutta la classifica →</Link></article></div></div></section>}

function Highlights({leagues}:{leagues:LeagueData[]}){const matches=leagues.flatMap(l=>l.matches),day=Math.max(0,...matches.filter(isCalculatedHomeMatch).map(m=>m.matchday));const daily=calculateGlobalMatchdayStats(matches,day||1),season=calculateSeasonStats(matches);return <section className="mx-auto max-w-7xl px-4 py-7 sm:px-6 sm:py-12"><Heading eyebrow="Il meglio e il peggio" title="La giornata"/><GlobalCards dayStats={daily} seasonStats={season} day={day||1} current/>{!day&&<p className="mt-3 text-center text-sm font-semibold text-slate-500">Disponibili dopo il calcolo della prima giornata.</p>}</section>}

function Championship({leagues,initial}:{leagues:LeagueData[];initial:LeagueId}){const [selected,setSelected]=useState(initial),league=leagues.find(l=>l.id===selected)??leagues[0];const rows=useMemo(()=>league&&latest(league)?standingsAt(league.teams,league.matches,latest(league)):[],[league]);if(!league)return null;return <section className="bg-white/65 py-7 sm:py-12"><div className="mx-auto max-w-7xl px-4 sm:px-6"><Heading eyebrow="Classifiche" title="I Campionati"/><div className="grid grid-cols-5 gap-1">{leagues.map(l=><button key={l.id} onClick={()=>setSelected(l.id)} className={`min-h-11 rounded-xl px-1 text-[9px] font-black uppercase ${selected===l.id?"bg-blue-950 text-white":"border bg-white text-blue-950"}`}>{l.id.startsWith("serie-c")?l.shortName:l.name}</button>)}</div><Rows rows={rows} leagueId={league.id}/><Link href="/campionati-live-preview?tab=results" className={`${cta} mt-4 w-full sm:w-full`}>Vedi tutti i risultati</Link></div></section>}
function thresholdLine(leagueId:LeagueId,position:number){if(leagueId==="serie-a")return position===1?"after:bg-gradient-to-r after:from-transparent after:via-amber-400 after:to-transparent":position===17?"after:bg-gradient-to-r after:from-transparent after:via-rose-500 after:to-transparent":"";if(leagueId==="serie-b")return position===3?"after:bg-gradient-to-r after:from-transparent after:via-emerald-500 after:to-transparent":position===16?"after:bg-gradient-to-r after:from-transparent after:via-rose-500 after:to-transparent":"";return position===1?"after:bg-gradient-to-r after:from-transparent after:via-emerald-500 after:to-transparent":""}
function Rows({rows,leagueId}:{rows:StandingRow[];leagueId:LeagueId}){const vals=rows.map(r=>r.fantasyPoints),max=Math.max(...vals),min=Math.min(...vals),colored=max!==min;return <div className="mt-3 overflow-hidden rounded-[1.35rem] bg-white shadow-sm"><ChampionshipTableHead/><div className="max-h-[280px] overflow-y-auto overscroll-contain">{rows.map(r=><Link key={r.id} href={`/societa/${r.slug}`} className={`relative grid min-h-14 grid-cols-[44px_32px_minmax(0,1fr)_34px_34px_54px] items-center gap-1 border-b border-slate-100 px-2 after:pointer-events-none after:absolute after:inset-x-2 after:bottom-0 after:h-px last:border-0 ${thresholdLine(leagueId,r.position)}`}><span className="relative flex items-center justify-center"><b className="text-center text-xs text-slate-500">{r.position}</b><Move value={r.movement}/></span><Image src={r.logo} alt="" width={32} height={32}/><span className="min-w-0 text-[10px] font-black uppercase text-blue-950"><AutoScrollName name={r.name}/></span><Destination row={r} leagueId={leagueId}/><b className="text-center text-xs">{r.points}</b><b className={`text-right text-xs ${colored&&r.fantasyPoints===max?"text-emerald-600":colored&&r.fantasyPoints===min?"text-rose-700":"text-slate-600"}`}>{r.fantasyPoints.toFixed(1)}</b></Link>)}{!rows.length&&<div className="relative overflow-hidden px-3 py-6 text-center"><span className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(56,189,248,.08),transparent_65%)]"/><p className="relative text-[8px] font-black uppercase leading-5 tracking-[.08em] text-blue-950 sm:text-xs sm:leading-6"><span className="block whitespace-nowrap">LA CLASSIFICA SARÀ DISPONIBILE</span><span className="block whitespace-nowrap">AL TERMINE DELLA PRIMA GIORNATA</span></p></div>}</div></div>}
function ChampionshipTableHead(){return <div className="grid grid-cols-[44px_32px_minmax(0,1fr)_34px_34px_54px] items-center gap-1 bg-slate-50/80 px-2 py-2 text-[8px] font-black uppercase text-slate-400"><span className="text-center">POS</span><span/><span>SQ</span><span/><span className="text-center">PT</span><span className="text-right">PT TOT</span></div>}
function CupTableHead(){return <div className="grid grid-cols-[44px_32px_minmax(0,1fr)_36px_58px] items-center gap-1 bg-slate-50/80 px-2 py-2 text-[8px] font-black uppercase text-slate-400"><span className="text-center">POS</span><span/><span>SQ</span><span className="text-center">PT</span><span className="text-right">PT TOT</span></div>}

function Cup({data}:{data:HomeLiveData}){const played=data.coppa.matches.filter(isCalculatedCoppaMatch),day=played.length?Math.max(...played.map(m=>m.day)):0,rows=day?coppaStandingsForRange(data.coppa.teams,data.coppa.matches,1,day):[];const own=rows.find(r=>r.id===data.viewer.teamId);return <section className="mx-auto max-w-7xl px-4 py-7 sm:px-6 sm:py-12"><header className="mb-5 sm:mb-8"><p className="section-eyebrow">Il torneo assoluto</p><h2 className="font-onder-title mt-3 flex flex-col text-3xl uppercase leading-none text-blue-950 sm:text-5xl"><span>La Coppa</span><span className="mt-3">Fanta a 20</span></h2></header>{own&&<Link href={`/societa/${own.slug}`} className="mb-3 flex min-h-12 items-center gap-3 rounded-xl bg-blue-950 px-4 text-white shadow-lg"><Image src={own.logo} alt="" width={32} height={32}/><span className="min-w-0 flex-1"><small className="block text-[8px] font-black uppercase text-sky-300">La tua squadra</small><b className="block truncate text-xs uppercase">{own.name}</b></span><strong>{own.position}°</strong></Link>}{rows.length?<><CupRows rows={rows}/><Link href="/coppe" className={`${cta} mt-4 w-full sm:w-auto`}>Vedi tutti i risultati</Link></>:<div className="relative overflow-hidden rounded-[1.35rem] bg-white px-4 py-7 text-center shadow-sm"><span className="absolute inset-0 bg-[radial-gradient(circle_at_center,rgba(245,158,11,.10),transparent_65%)]"/><p className="relative text-xs font-black uppercase tracking-[.16em] text-amber-700 sm:text-sm">LA COMPETIZIONE STA PER ARRIVARE..</p></div>}</section>}
function CupRows({rows}:{rows:ReturnType<typeof coppaStandingsForRange>}){const vals=rows.map(r=>r.totalPoints),max=Math.max(...vals),min=Math.min(...vals),colored=max!==min;return <div className="overflow-hidden rounded-[1.35rem] bg-white shadow-sm"><CupTableHead/><div className="max-h-[280px] overflow-y-auto">{rows.map(r=><div key={r.id} className="relative"><Link href={`/societa/${r.slug}`} className="grid min-h-14 grid-cols-[44px_32px_minmax(0,1fr)_36px_58px] items-center gap-1 border-b border-slate-100 px-2 last:border-0"><span className="relative flex items-center justify-center"><b className="text-center text-xs text-slate-500">{r.position}</b><Move value={r.movement}/></span><Image src={r.logo} alt="" width={32} height={32}/><span className="min-w-0 text-[10px] font-black uppercase text-blue-950"><AutoScrollName name={r.name}/></span><b className="text-center text-xs">{r.points}</b><b className={`text-right text-xs ${colored&&r.totalPoints===max?"text-emerald-600":colored&&r.totalPoints===min?"text-rose-700":"text-slate-600"}`}>{r.totalPoints.toFixed(1)}</b></Link>{qualificationSeparators.has(r.position)&&<div className="pointer-events-none absolute inset-x-0 bottom-0 flex translate-y-1/2 items-center gap-1 px-2 text-[7px] font-black uppercase text-amber-700"><i className="h-px flex-1 bg-amber-400"/><span className="bg-white px-1">{qualificationSeparators.get(r.position)?.mobile}</span><i className="h-px flex-1 bg-amber-400"/></div>}</div>)}</div></div>}
