import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { FANTABET_ADMIN_SEASON, STANDARD_V1_POINTS, STANDARD_V1_TYPES, confirmedSubmissionsLabel, isAdminRoundEditable, roundCompletion, validateAdminRound, type AdminRoundInput } from "./admin.ts";

function valid(): AdminRoundInput { return { stagioneId: 1, giornata: 7, opensAt: "2026-08-10T10:00:00.000Z", deadlineAt: "2026-08-12T10:00:00.000Z", bets: STANDARD_V1_TYPES.map((type, index) => ({ partitaId: index + 1, type, points: STANDARD_V1_POINTS[type], order: index + 1 })) }; }

test("admin valida cinque partite distinte e formato V1", () => { assert.deepEqual(validateAdminRound(valid()), []); const four = valid(); four.bets.pop(); assert.match(validateAdminRound(four).join(" "), /esattamente 5/); const duplicate = valid(); duplicate.bets[4].partitaId = 1; assert.match(validateAdminRound(duplicate).join(" "), /distinte/); const points = valid(); points.bets[0].points = 4; assert.match(validateAdminRound(points).join(" "), /punti/); });
test("admin valida stagione giornata e deadline strettamente successiva", () => { const input = valid(); input.stagioneId = 0; input.giornata = 0; input.deadlineAt = input.opensAt; const errors = validateAdminRound(input).join(" "); assert.match(errors, /stagione/); assert.match(errors, /giornata/); assert.match(errors, /deadline/); });
test("percentuale monitoraggio è derivata senza Auth", () => { assert.equal(roundCompletion(0, 0), 0); assert.equal(roundCompletion(4, 3), 75); });
test("schedine giocate mostra soltanto l'intero confermato", () => { assert.equal(confirmedSubmissionsLabel(0), "0"); assert.equal(confirmedSubmissionsLabel(1), "1"); assert.equal(confirmedSubmissionsLabel(49), "49"); });
test("round pubblicata è modificabile soltanto prima di opens_at", () => { const now = new Date("2026-08-10T10:00:00Z"); assert.equal(isAdminRoundEditable({ status: "pubblicata", opensAt: "2026-08-10T11:00:00Z" }, now), true); assert.equal(isAdminRoundEditable({ status: "pubblicata", opensAt: "2026-08-10T10:00:00Z" }, now), false); assert.equal(isAdminRoundEditable({ status: "bozza", opensAt: "2020-01-01T00:00:00Z" }, now), true); });

test("route usa autorizzazione e header admin condiviso", async () => { const page = await readFile(new URL("../../app/admin/fantabet/page.tsx", import.meta.url), "utf8"); const actions = await readFile(new URL("../../app/admin/fantabet/actions.ts", import.meta.url), "utf8"); const header = await readFile(new URL("../../app/admin/AdminHeader.tsx", import.meta.url), "utf8"); const auth = await readFile(new URL("../admin-import/auth.server.ts", import.meta.url), "utf8"); assert.match(page, /requireImportAdmin\(\).*redirect\("\/account\/accedi"\)/s); assert.match(actions, /await requireImportAdmin\(\)/); assert.match(page, /AdminHeader.*Gestione FantaBet.*username=\{access\.username\}.*Centro Admin/s); assert.match(header, /grid-cols-\[minmax\(0,1fr\)_auto\]/); assert.match(header, /username \|\| "Admin"/); assert.doesNotMatch(header, /\bemail\b/); assert.match(auth, /evaluateAdminIdentity[\s\S]*from\("profiles"\)\.select\("username"\)/); assert.doesNotMatch(page + actions, /ADMIN_IMPORT_EMAILS|auth\.users/); });
test("action ammette bozza e pubblicata pre-open ma non bypassa trigger", async () => { const actions = await readFile(new URL("../../app/admin/fantabet/actions.ts", import.meta.url), "utf8"); assert.match(actions, /status === "bozza".*status === "pubblicata".*Date\.now\(\).*opens_at/s); assert.match(actions, /update\(\{ status: "pubblicata" \}\).*eq\("status", "bozza"\)/s); assert.doesNotMatch(actions, /disable.*trigger|session_replication_role/i); });
test("UI admin inizia con Compila la schedina e termina con Schedine pubblicate", async () => { const client = await readFile(new URL("../../app/admin/fantabet/AdminFantaBetClient.tsx", import.meta.url), "utf8"); for (const text of ["Compila la schedina", "Seleziona 5 partite", "Sposta su", "Sposta giù", "ANTEPRIMA", "PUBBLICA", "Schedine pubblicate", "Schedine giocate"]) assert.match(client, new RegExp(text, "i")); assert.doesNotMatch(client, /Round più recente|>NUOVA</); assert.ok(client.indexOf("Compila la schedina") < client.indexOf("Schedine pubblicate")); assert.equal(FANTABET_ADMIN_SEASON, "2026/27"); assert.match(client, /initial\.season\.label/); assert.match(client, /Array\.from\(\{ length: 38 \}/); assert.match(client, /SERIE C · GIRONE/); assert.match(client, /match\.league === league/); assert.match(client, /min=\{opensAt \|\| undefined\}/); assert.match(client, /sort\(\(a, b\) => a\.giornata - b\.giornata/); assert.match(client, /confirmedSubmissionsLabel\(round\.confirmed\)/); assert.doesNotMatch(client, /DeadlineCountdown|Tempo residuo|STANDARD V1/); });
test("Visualizza usa id round e storico è a selezione singola", async () => { const client = await readFile(new URL("../../app/admin/fantabet/AdminFantaBetClient.tsx", import.meta.url), "utf8"); assert.match(client, /href=\{`\/fantabet\?round=\$\{round\.id\}`\}/); assert.match(client, /selectedId.*onSelect/s); assert.doesNotMatch(client, /rounds\.map\(\(round\) => <article/); });
test("monitoraggio usa prediction e submission senza email", async () => { const server = await readFile(new URL("./admin.server.ts", import.meta.url), "utf8"); assert.match(server, /grouped\.set/); assert.match(server, /fantabet_round_submissions/); assert.match(server, /competizioni.*divisione_riferimento/s); assert.doesNotMatch(server, /auth\.users|select\([^)]*email/i); });
test("migrazione correttiva congela configurazione da opens_at", async () => { const sql = await readFile(new URL("../../../supabase/migrations/202608090001_fantabet_preopen_editing.sql", import.meta.url), "utf8"); assert.match(sql, /statement_timestamp\(\) < old\.opens_at/); assert.match(sql, /round_status = 'pubblicata' and statement_timestamp\(\) < round_opens_at/); assert.match(sql, /FANTABET_CONFIGURAZIONE_APERTA_IMMUTABILE/); assert.match(sql, /revoke all.*authenticated/is); });
