"use client";
import Image from "next/image";
import Link from "next/link";
import { useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { FantaBetType } from "@/lib/fantabet/types";
import { STANDARD_V1_POINTS, STANDARD_V1_TYPES, confirmedSubmissionsLabel, isAdminRoundEditable, validateAdminRound, type AdminBetInput, type AdminRoundInput } from "@/lib/fantabet/admin";
import type { AdminMatch, AdminRound, FantaBetAdminData } from "@/lib/fantabet/admin.server";
import { publishFantaBetRoundAction, saveFantaBetDraftAction } from "./actions";

const typeLabels: Record<FantaBetType, string> = { "1X2": "1X2", UNDER_OVER_2_5: "U/O 2.5", RISULTATO_ESATTO: "Ris. esatto", FANTAPUNTEGGIO_1X2: "Fanta PT" };
const leagues = ["Serie A", "Serie B", "Serie C Girone A", "Serie C Girone B", "Serie C Girone C"];
function leagueLabel(value: string) { return value.replace(/^Serie C Girone /, "SERIE C · GIRONE ").toUpperCase(); }
function localValue(value?: string) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }

export default function AdminFantaBetClient({ initial }: { initial: FantaBetAdminData }) {
  const router = useRouter(); const [pending, startTransition] = useTransition();
  const editableInitial = initial.rounds.find((round) => isAdminRoundEditable(round, new Date(initial.serverNow)));
  const [roundId, setRoundId] = useState<number | null>(editableInitial?.id ?? null);
  const [day, setDay] = useState(editableInitial?.giornata ?? 1);
  const [opensAt, setOpensAt] = useState(localValue(editableInitial?.opensAt));
  const [deadlineAt, setDeadlineAt] = useState(localValue(editableInitial?.deadlineAt));
  const [bets, setBets] = useState<AdminBetInput[]>(() => editableInitial?.bets.map((bet) => ({ partitaId: bet.partitaId, type: bet.type as FantaBetType, points: bet.points, order: bet.order })) ?? []);
  const [league, setLeague] = useState(() => initial.matches.find((match) => editableInitial?.bets.some((bet) => bet.partitaId === match.id))?.league || leagues[0]);
  const [historyId, setHistoryId] = useState(initial.rounds[0]?.id ?? 0);
  const [message, setMessage] = useState(""); const [preview, setPreview] = useState(false);
  const matches = useMemo(() => initial.matches.filter((match) => match.stagioneId === initial.season.id && match.giornata === day && match.league === league), [initial.matches, initial.season.id, day, league]);
  const input: AdminRoundInput = { roundId, stagioneId: initial.season.id, giornata: day, opensAt: opensAt ? new Date(opensAt).toISOString() : "", deadlineAt: deadlineAt ? new Date(deadlineAt).toISOString() : "", bets };
  const errors = validateAdminRound(input);
  function changeDay(next: number) { setDay(Math.min(38, Math.max(1, next))); setBets([]); setRoundId(null); }
  function toggleMatch(matchId: number) { setBets((value) => { const existing = value.some((bet) => bet.partitaId === matchId); if (existing) return value.filter((bet) => bet.partitaId !== matchId).map((bet, index) => ({ ...bet, order: index + 1 })); if (value.length >= 5) return value; const type = STANDARD_V1_TYPES[value.length]; return [...value, { partitaId: matchId, type, points: STANDARD_V1_POINTS[type], order: value.length + 1 }]; }); }
  function changeType(index: number, type: FantaBetType) { setBets((value) => value.map((bet, position) => position === index ? { ...bet, type, points: STANDARD_V1_POINTS[type] } : bet)); }
  function move(index: number, delta: number) { setBets((value) => { const target = index + delta; if (target < 0 || target >= value.length) return value; const next = [...value]; [next[index], next[target]] = [next[target], next[index]]; return next.map((bet, order) => ({ ...bet, order: order + 1 })); }); }
  function edit(round: AdminRound) { if (!isAdminRoundEditable(round, new Date(initial.serverNow))) return; setRoundId(round.id); setDay(round.giornata); setOpensAt(localValue(round.opensAt)); setDeadlineAt(localValue(round.deadlineAt)); setBets(round.bets.map((bet) => ({ partitaId: bet.partitaId, type: bet.type as FantaBetType, points: bet.points, order: bet.order }))); setLeague(initial.matches.find((match) => round.bets.some((bet) => bet.partitaId === match.id))?.league || leagues[0]); window.scrollTo({ top: 0, behavior: "smooth" }); }
  function save() { startTransition(async () => { const result = await saveFantaBetDraftAction(JSON.stringify(input)); setMessage(result.message); if (result.ok) { setRoundId(result.roundId ?? null); router.refresh(); } }); }
  function publish() { if (!roundId || errors.length || !window.confirm(`Pubblicare la schedina G${day} con 5 giocate? Sarà modificabile soltanto fino all’apertura.`)) return; startTransition(async () => { const result = await publishFantaBetRoundAction(roundId); setMessage(result.message); if (result.ok) router.refresh(); }); }
  return <div className="space-y-4">
    <section className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm sm:p-5"><h2 className="text-lg font-black uppercase text-blue-950">Compila la schedina</h2>
      <div className="mt-4 grid grid-cols-[minmax(0,1fr)_auto] items-end gap-3"><Field label="Stagione"><strong className="block min-h-11 rounded-xl bg-slate-50 px-3 py-3 text-sm text-blue-950">{initial.season.label}</strong></Field><DayPicker day={day} onChange={changeDay} /></div>
      <div className="mt-3 grid grid-cols-2 gap-3"><Field label="Apertura"><input type="datetime-local" value={opensAt} onChange={(event) => { setOpensAt(event.target.value); if (deadlineAt && deadlineAt <= event.target.value) setDeadlineAt(""); }} className="admin-input" /></Field><Field label="Chiusura"><input type="datetime-local" min={opensAt || undefined} value={deadlineAt} onChange={(event) => setDeadlineAt(event.target.value)} className="admin-input" /></Field></div>
      <div className="mt-4"><Field label="Lega"><select value={league} onChange={(event) => { setLeague(event.target.value); setBets([]); }} className="admin-input">{leagues.map((item) => <option key={item} value={item}>{leagueLabel(item)}</option>)}</select></Field></div>
      <h3 className="mt-5 text-sm font-black uppercase text-blue-950">Seleziona 5 partite <span className="text-sky-700">({bets.length}/5)</span></h3>
      <div className="mt-2 grid gap-2 sm:grid-cols-2">{matches.length ? matches.map((match) => <MatchChoice key={match.id} match={match} selected={bets.some((bet) => bet.partitaId === match.id)} disabled={bets.length >= 5 && !bets.some((bet) => bet.partitaId === match.id)} onClick={() => toggleMatch(match.id)} />) : <p className="text-sm font-semibold text-slate-500">Nessuna partita reale per lega e giornata selezionate.</p>}</div>
      {bets.length > 0 && <div className="mt-4 space-y-2">{bets.map((bet, index) => { const match = initial.matches.find((item) => item.id === bet.partitaId); return <div key={bet.partitaId} className="grid grid-cols-[24px_minmax(0,1fr)_110px_72px] items-center gap-2 rounded-xl border border-slate-200 p-2"><strong>{index + 1}</strong><span className="truncate text-[11px] font-black">{match ? `${match.home.name} – ${match.away.name}` : bet.partitaId}</span><select value={bet.type} onChange={(event) => changeType(index, event.target.value as FantaBetType)} className="admin-input">{Object.entries(typeLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><span className="flex gap-1"><button aria-label="Sposta su" disabled={index === 0} onClick={() => move(index, -1)} className="admin-move">↑</button><button aria-label="Sposta giù" disabled={index === bets.length - 1} onClick={() => move(index, 1)} className="admin-move">↓</button></span></div>; })}</div>}
      {errors.length > 0 && <ul className="mt-3 rounded-xl bg-rose-50 p-3 text-xs font-bold text-rose-700">{errors.map((error) => <li key={error}>• {error}</li>)}</ul>}
      <div className="mt-4 flex flex-wrap gap-2"><button disabled={pending || errors.length > 0} onClick={save} className="admin-primary">SALVA</button><button disabled={errors.length > 0} onClick={() => setPreview(true)} className="admin-secondary">ANTEPRIMA</button>{initial.rounds.find((round) => round.id === roundId)?.status !== "pubblicata" && <button disabled={pending || !roundId || errors.length > 0} onClick={publish} className="admin-publish">PUBBLICA</button>}</div>{message && <p aria-live="polite" className="mt-3 text-sm font-bold text-slate-600">{message}</p>}
    </section>
    <RoundHistory rounds={initial.rounds} selectedId={historyId} onSelect={setHistoryId} onEdit={edit} now={new Date(initial.serverNow)} />
    {preview && <Preview input={input} matches={initial.matches} onClose={() => setPreview(false)} />}
    <style jsx global>{`.admin-input{min-height:42px;width:100%;border:1px solid #cbd5e1;border-radius:.65rem;background:#fff;padding:.45rem .6rem;font-size:.75rem;font-weight:700}.admin-primary,.admin-secondary,.admin-publish{min-height:42px;border-radius:.75rem;padding:.55rem .9rem;font-size:.72rem;font-weight:900}.admin-primary{background:#172554;color:#fff}.admin-secondary{border:1px solid #94a3b8;background:#fff;color:#172554}.admin-publish{background:#059669;color:#fff}.admin-primary:disabled,.admin-secondary:disabled,.admin-publish:disabled{opacity:.35}.admin-move{height:32px;width:32px;border-radius:.5rem;background:#f1f5f9;font-weight:900}.admin-move:disabled{opacity:.25}`}</style>
  </div>;
}

function DayPicker({ day, onChange }: { day: number; onChange: (day: number) => void }) { return <div><p className="text-xs font-black uppercase text-slate-600">Giornata</p><div className="mt-1 flex h-11 items-center rounded-xl border border-slate-300"><button aria-label="Giornata precedente" disabled={day <= 1} onClick={() => onChange(day - 1)} className="h-full w-9 font-black disabled:opacity-25">‹</button><select aria-label="Seleziona giornata" value={day} onChange={(event) => onChange(Number(event.target.value))} className="h-full appearance-none bg-white px-2 text-center text-xs font-black">{Array.from({ length: 38 }, (_, index) => index + 1).map((value) => <option key={value} value={value}>GIORNATA {value}</option>)}</select><button aria-label="Giornata successiva" disabled={day >= 38} onClick={() => onChange(day + 1)} className="h-full w-9 font-black disabled:opacity-25">›</button></div></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs font-black uppercase text-slate-600">{label}<span className="mt-1 block">{children}</span></label>; }
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-[9px] font-black uppercase text-slate-500">{label}</p><p className="mt-1 text-xs font-black text-blue-950">{value}</p></div>; }
function MatchChoice({ match, selected, disabled, onClick }: { match: AdminMatch; selected: boolean; disabled: boolean; onClick: () => void }) { return <button disabled={disabled} onClick={onClick} className={`grid min-h-14 grid-cols-[28px_minmax(0,1fr)_auto_minmax(0,1fr)_28px] items-center gap-1.5 rounded-xl border p-2 text-[11px] font-black disabled:opacity-35 ${selected ? "border-sky-500 bg-sky-50" : "border-slate-200 bg-white"}`}><Image src={match.home.logo} alt="" width={28} height={28} unoptimized className="h-7 w-7 object-contain" /><span className="truncate text-right">{match.home.name}</span><span className="text-slate-400">vs</span><span className="truncate text-left">{match.away.name}</span><Image src={match.away.logo} alt="" width={28} height={28} unoptimized className="h-7 w-7 object-contain" /></button>; }
function RoundHistory({ rounds, selectedId, onSelect, onEdit, now }: { rounds: AdminRound[]; selectedId: number; onSelect: (id: number) => void; onEdit: (round: AdminRound) => void; now: Date }) { const ordered = [...rounds].sort((a, b) => a.giornata - b.giornata || a.id - b.id); const selectedIndex = ordered.findIndex((round) => round.id === selectedId); const index = selectedIndex < 0 ? 0 : selectedIndex; const round = ordered[index]; if (!round) return null; return <section className="rounded-2xl border border-slate-200 bg-white p-3"><h2 className="text-lg font-black uppercase text-blue-950">Schedine pubblicate</h2><div className="mt-3 flex items-center justify-center"><button aria-label="Round precedente" disabled={index <= 0} onClick={() => onSelect(ordered[index - 1].id)} className="h-10 w-10 font-black disabled:opacity-25">‹</button><select aria-label="Seleziona schedina pubblicata" value={round.id} onChange={(event) => onSelect(Number(event.target.value))} className="admin-input max-w-56 text-center">{ordered.map((item) => <option key={item.id} value={item.id}>G{item.giornata} · {item.status.toUpperCase()}</option>)}</select><button aria-label="Round successiva" disabled={index >= ordered.length - 1} onClick={() => onSelect(ordered[index + 1].id)} className="h-10 w-10 font-black disabled:opacity-25">›</button></div><div className="mt-3 grid grid-cols-2 gap-3"><Metric label="Data inizio" value={new Date(round.opensAt).toLocaleString("it-IT")} /><Metric label="Data fine" value={new Date(round.deadlineAt).toLocaleString("it-IT")} /></div><div className="mt-3 flex items-center justify-between border-t border-slate-100 pt-3"><Metric label="Schedine giocate" value={confirmedSubmissionsLabel(round.confirmed)} /><div className="flex gap-3">{isAdminRoundEditable(round, now) && <button onClick={() => onEdit(round)} className="text-xs font-black text-sky-700">MODIFICA</button>}{round.status !== "bozza" && <Link href={`/fantabet?round=${round.id}`} className="text-xs font-black text-sky-700">VISUALIZZA</Link>}</div></div></section>; }
function Preview({ input, matches, onClose }: { input: AdminRoundInput; matches: AdminMatch[]; onClose: () => void }) { return <div role="dialog" aria-modal="true" aria-label="Anteprima schedina" className="fixed inset-0 z-50 grid place-items-center bg-blue-950/70 p-3"><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-4"><div className="flex justify-between"><h2 className="text-xl font-black uppercase text-blue-950">Anteprima · G{input.giornata}</h2><button onClick={onClose} aria-label="Chiudi anteprima" className="text-2xl">×</button></div><p className="mt-2 text-xs font-bold text-slate-500">Apre {new Date(input.opensAt).toLocaleString("it-IT")} · chiude {new Date(input.deadlineAt).toLocaleString("it-IT")}</p><div className="mt-4 space-y-2">{[...input.bets].sort((a,b) => a.order-b.order).map((bet) => { const match = matches.find((item) => item.id === bet.partitaId); return <article key={bet.partitaId} className="grid grid-cols-[70px_minmax(0,1fr)_45px] items-center rounded-xl border border-slate-200 p-3"><strong className="text-xs text-sky-700">{typeLabels[bet.type]}</strong><span className="truncate text-center text-xs font-black">{match?.home.name} vs {match?.away.name}</span><strong className="text-right text-xs">{bet.points}</strong></article>; })}</div><p className="mt-4 rounded-xl bg-amber-50 p-3 text-xs font-bold text-amber-900">L’anteprima non salva pronostici e non pubblica la round.</p></div></div>; }
