import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import type { LeagueData, Match, Team } from "@/app/campionati-live-preview/types";
import { fantaBetHomeState, selectHomeMatchState } from "./logic.ts";

const alpha: Team = { id: 1, name: "PALERMAVAI MA VIENI MA CHI SONO", logo: "/a.png", slug: "alpha" };
const beta: Team = { id: 2, name: "BRIGHTON & HOVE ALBIONOLEFFE", logo: "/b.png", slug: "beta" };
function match(day: number, status: string): Match { return { id: String(day), matchday: day, serieAMatchday: day, home: alpha, away: beta, homeGoals: status === "calcolata" ? 2 : null, awayGoals: status === "calcolata" ? 1 : null, homeScore: status === "calcolata" ? 72 : null, awayScore: status === "calcolata" ? 66.5 : null, status }; }
function league(matches: Match[]): LeagueData { return { id: "serie-c-b", competitionCode: "serie-c-girone-b", name: "Serie C Girone B", shortName: "C Gir B", found: true, initialMatchday: 1, availableMatchdays: [1, 2], teams: [alpha, beta], matches }; }

test("prima della Giornata 1 mostra direttamente la prossima partita", () => { const state = selectHomeMatchState([league([match(1, "programmata")])], 1); assert.equal(state.last, null); assert.equal(state.next?.matchday, 1); assert.equal(state.team?.id, 1); });
test("dopo i risultati mostra ultima partita e prossima della società personale", () => { const state = selectHomeMatchState([league([match(1, "calcolata"), match(2, "programmata")])], 1); assert.equal(state.last?.matchday, 1); assert.equal(state.next?.matchday, 2); assert.equal(state.league?.id, "serie-c-b"); });
test("anonimo o utente senza squadra usa una situazione generale senza card rotta", () => { const state = selectHomeMatchState([league([match(1, "programmata")])], null); assert.equal(state.team, null); assert.equal(state.next?.matchday, 1); });
test("FantaBet distingue assente, aperta anon, aperta auth, giocata e chiusa", () => { const now = "2026-08-14T10:00:00.000Z"; const round = { id: 7, number: 3, status: "pubblicata", opensAt: "2026-08-14T09:00:00.000Z", deadlineAt: "2026-08-15T09:00:00.000Z" }; assert.equal(fantaBetHomeState(null, false, null, now).state, "missing"); assert.match(fantaBetHomeState(round, false, null, now).href, /returnTo/); assert.equal(fantaBetHomeState(round, false, "user", now).state, "open"); assert.equal(fantaBetHomeState(round, true, "user", now).state, "submitted"); assert.equal(fantaBetHomeState({ ...round, deadlineAt: "2026-08-14T09:30:00.000Z" }, false, "user", now).state, "closed"); });

test("Home mantiene Hero esatta a tre righe e porta sport e FantaBet subito dopo", async () => { const page = await readFile(new URL("../../app/page.tsx", import.meta.url), "utf8"); for (const text of ["NON E&apos; SOLO", "FANTACALCIO", "E&apos; IL FANTA A 20", "HomeLiveSections", "Le protagoniste", "I giochi", "I record", "Gli Emblemi", "La struttura", "La Lista di Attesa", "Scarica il regolamento"]) assert.match(page, new RegExp(text, "i")); assert.doesNotMatch(page.slice(page.indexOf("font-onder-hero"), page.indexOf("HomeLiveSections data=")), /NON È|FANTACALCIO\./); assert.ok(page.indexOf("HomeLiveSections") < page.indexOf("Le protagoniste")); assert.ok(page.lastIndexOf('href="/storia"') > page.indexOf("La Lista di Attesa")); });
test("Home mostra Classifiche con I Campionati e pagina Regolamento usa il nome La Struttura", async () => { const client = await readFile(new URL("../../app/HomeLiveSections.tsx", import.meta.url), "utf8"); const page = await readFile(new URL("../../app/regolamento/page.tsx", import.meta.url), "utf8"); const layout = await readFile(new URL("../../app/regolamento/layout.tsx", import.meta.url), "utf8"); assert.match(client, /<Heading eyebrow="Classifiche" title="I Campionati"\/>/); assert.doesNotMatch(client, /eyebrow="Risultati e classifiche"/); assert.match(page, /title="La Struttura"/); assert.match(layout, /title: "La Struttura"/); });
test("CTA risultati conserva il mobile e diventa full width su desktop", async () => { const client = await readFile(new URL("../../app/HomeLiveSections.tsx", import.meta.url), "utf8"); const cta = client.match(/<Link href="\/campionati-live-preview\?tab=results"[\s\S]*?Vedi tutti i risultati<\/Link>/)?.[0] ?? ""; assert.match(cta, /w-full sm:w-full/); assert.doesNotMatch(cta, /sm:w-auto/); });
test("contenuti precampionato usano i copy definitivi senza spiegazioni aggiuntive", async () => { const client = await readFile(new URL("../../app/HomeLiveSections.tsx", import.meta.url), "utf8"); for (const text of ["La corsa al vertice inizierà", "LA CLASSIFICA SARÀ DISPONIBILE", "AL TERMINE DELLA PRIMA GIORNATA", "LA COMPETIZIONE STA PER ARRIVARE\\.\\."]) assert.match(client, new RegExp(text)); assert.doesNotMatch(client, /La classifica prenderà forma|Al via dalla terza giornata/); assert.match(client, /<GlobalCards/); });
test("classifiche Home sono complete, scrollabili e usano simboli e marquee esistenti", async () => { const client = await readFile(new URL("../../app/HomeLiveSections.tsx", import.meta.url), "utf8"); const marquee = await readFile(new URL("../../app/ranking/AutoScrollName.tsx", import.meta.url), "utf8"); assert.match(client, /max-h-\[280px\] overflow-y-auto/); assert.match(client, /Scatto Promozione/); assert.match(client, /fantasyPoints===max/); assert.match(client, /fantasyPoints===min/); assert.match(client, /AutoScrollName name=\{r\.name\}/); assert.match(marquee, /scrollWidth - container\.clientWidth/); assert.match(marquee, /prefers-reduced-motion/); });
test("Coppa ha titolo mobile su due righe e collegamento ai risultati", async () => { const client = await readFile(new URL("../../app/HomeLiveSections.tsx", import.meta.url), "utf8"); assert.match(client, /<span>La Coppa<\/span><span className="mt-3">Fanta a 20<\/span>/); assert.match(client, /href="\/coppe"/); assert.match(client, /Vedi tutti i risultati/); });
test("tabelle Home allineano header e righe, mostrano 100 team Coppa e sole soglie richieste", async () => { const client = await readFile(new URL("../../app/HomeLiveSections.tsx", import.meta.url), "utf8"); assert.match(client, /grid-cols-\[44px_32px_minmax\(0,1fr\)_34px_34px_54px\]/); assert.doesNotMatch(client, /slice\(0,20\)/); for (const condition of ['position===1', 'position===17', 'position===3', 'position===16']) assert.match(client, new RegExp(condition)); assert.doesNotMatch(client, /border-y/); });
test("giochi mobile restano in due colonne senza titoli sotto le immagini", async () => { const page = await readFile(new URL("../../app/page.tsx", import.meta.url), "utf8"); const games = page.slice(page.indexOf('eyebrow="Mettiti alla prova"'), page.indexOf('eyebrow="Storia e prestigio"')); assert.match(games, /grid grid-cols-2 gap-3/); for (const text of ["Entra nel FantaBet", "Gioca ora"]) assert.match(games, new RegExp(text)); assert.doesNotMatch(games, /item\.title|<h3/); });
test("pagina Storia usa tre capitoli indipendenti e mantiene il finale sempre aperto", async () => { const page = await readFile(new URL("../../app/storia/page.tsx", import.meta.url), "utf8"); const chapters = await readFile(new URL("../../app/storia/StoryChapters.tsx", import.meta.url), "utf8"); const modal = await readFile(new URL("../../app/components/ContactDialog.tsx", import.meta.url), "utf8"); for (const text of ["Dove tutto ha inizio", "DAL 2023", "DA UNA LEGA A UN PROGETTO", "LA STORIA PRENDE FORMA", "Cento Società. Un solo mondo.", "OGGI, IN 100"]) assert.ok(chapters.includes(text)); assert.equal((chapters.match(/<StoryChapter /g) ?? []).length, 3); for (const text of ["venti partecipanti, venti rose e nessun calciatore doppione", "È da lì che comincia la nostra storia.", "Il gioco continua, ma ciò che accade comincia a restare.", "100 Società in cinque leghe", "Ranking Storico, Hall of Fame, Emblemi, competizioni e storie delle Società"]) assert.ok(chapters.includes(`<strong className="font-black text-blue-950">${text}</strong>`)); for (const token of ["useState(false)", "aria-expanded={expanded}", "aria-controls={contentId}", "Espandi", "Riduci", "grid-rows-[0fr]", "motion-reduce:transition-none"]) assert.ok(chapters.includes(token)); assert.match(page, /IL PROSSIMO CAPITOLO/); assert.match(page, /COSTRUIAMOLO INSIEME/); assert.match(page, /diventare partner, collaborare con noi o portare la tua realtà dentro questo mondo/); assert.doesNotMatch(page, /aria-expanded/); assert.match(modal, /Basta un click!/); assert.match(modal, /absolute left-4 top-1\/2/); assert.doesNotMatch(modal, /→|chevron/); });
test("loader condivide catalogo e parallelizza le fonti principali senza fallback fake production", async () => { const loader = await readFile(new URL("./data.server.ts", import.meta.url), "utf8"); const config = await readFile(new URL("../demo-data/config.ts", import.meta.url), "utf8"); assert.match(loader, /catalogOverride \?\? await getActiveSocietaCatalog\(\)/); assert.match(loader, /Promise\.all\(/); assert.match(loader, /loadChampionshipData\(undefined, catalog\)/); assert.match(loader, /loadActiveCoppaData\(catalog\)/); assert.match(config, /NODE_ENV !== "production"/); });
