"use client";
import { useMemo, useState, useTransition } from "react";
import type { LineupAdminRound, LineupPreview, LineupPreviewTeam, LineupSlot, MatchStatus, PlayerMatch, RosterPlayer } from "@/lib/fantabet-lineups/types";
import { analyzeLineupScreenshotAction, confirmLineupsAction } from "./actions";
import { validateConfirmation } from "@/lib/fantabet-lineups/logic";

const statusLabel: Record<MatchStatus, string> = { recognized: "✓ Riconosciuto", ambiguous: "⚠ Ambiguo", unrecognized: "✕ Non riconosciuto" };

function slotIncomplete(slot: LineupSlot | null, societyId: number, roster: RosterPlayer[]) {
  if (!slot) return true;
  if (slot.source === "manual") return !slot.overrideConfirmed || !slot.player.trim();
  const inRoster = roster.some((player) => player.id === slot.rosterPlayerId && player.societyId === societyId);
  return !inRoster && !slot.overrideConfirmed;
}

export default function LineupsAdminClient({ rounds }: { rounds: LineupAdminRound[] }) {
  const [roundId, setRoundId] = useState(rounds[0]?.id ?? 0);
  const round = rounds.find((item) => item.id === roundId) ?? null;
  const [matchId, setMatchId] = useState(round?.matches[0]?.id ?? 0);
  const [preview, setPreview] = useState<LineupPreview | null>(null);
  const [message, setMessage] = useState("");
  const [analyzing, startAnalysis] = useTransition();
  const [saving, startSaving] = useTransition();
  function updateTeam(index: number, update: Partial<LineupPreviewTeam>) { setPreview((current) => current ? { ...current, teams: current.teams.map((team, i) => i === index ? { ...team, ...update } : team) as LineupPreview["teams"] } : current); }
  function analyze(formData: FormData) { setMessage(""); setPreview(null); startAnalysis(async () => { const result = await analyzeLineupScreenshotAction(formData); setMessage(result.message); if (result.preview) setPreview(result.preview); }); }
  const payload = useMemo(() => preview && ({ matchId: preview.matchId, seasonId: preview.seasonId, matchday: preview.matchday, teams: preview.teams.map((team) => ({ societyId: team.societyId ?? 0, formation: team.formation, players: team.players.map((player) => player.slot), captainOrder: team.captainId, viceCaptainOrder: team.viceCaptainId })) }), [preview]);
  const confirmDisabled = !preview || !payload || preview.teams.some((team) => { const roster = preview.options.find((option) => option.id === team.societyId)?.roster ?? []; return !team.societyId || team.players.length !== 11 || team.players.some((player) => slotIncomplete(player.slot, team.societyId!, roster)); }) || Boolean(validateConfirmation(payload, preview.options)) || saving;
  function confirm() { if (!payload || confirmDisabled) return; startSaving(async () => { const result = await confirmLineupsAction(JSON.stringify(payload)); setMessage(result.message); }); }
  if (!rounds.length) return <p>Configura prima una round FantaBet con cinque partite.</p>;
  return <div className="space-y-4">
    <form action={analyze} className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm sm:p-6">
      <label className="block text-xs font-black uppercase text-blue-950">Round FantaBet<select value={roundId} onChange={(event) => { const id=Number(event.target.value); const next=rounds.find((item)=>item.id===id); setRoundId(id); setMatchId(next?.matches[0]?.id??0); setPreview(null); }} className="mt-2 min-h-12 w-full rounded-xl border px-3">{rounds.map((item)=><option key={item.id} value={item.id}>G{item.matchday} · {item.status.toUpperCase()}</option>)}</select></label>
      <fieldset className="mt-5"><legend className="text-xs font-black uppercase">Scegli una delle 5 partite</legend>{round?.matches.map((match)=><label key={match.id} className="mt-2 flex min-h-12 items-center gap-3"><input type="radio" name="matchId" value={match.id} checked={matchId===match.id} onChange={()=>{setMatchId(match.id);setPreview(null);}}/>{match.home.name} — {match.away.name}</label>)}</fieldset>
      <label className="mt-5 block text-xs font-black uppercase">Screenshot<input name="screenshot" type="file" required accept="image/png,image/jpeg,image/webp" className="mt-2 block min-h-12 w-full"/></label>
      <button disabled={analyzing || !matchId} className="mt-4 min-h-12 w-full rounded-xl bg-blue-950 text-white">{analyzing ? "Analisi in corso…" : "Analizza screenshot"}</button>
    </form>
    {message && <p role="status" className="rounded-xl bg-sky-50 p-3">{message}</p>}
    {preview && <section className="space-y-4"><h2 className="text-xl font-black uppercase">Anteprima editabile</h2>{preview.teams.map((team, teamIndex) => { const option=preview.options.find((item)=>item.id===team.societyId); return <article key={teamIndex} className="rounded-2xl border bg-white p-4"><p className="text-xs text-slate-500">Letto: {team.detectedName||"—"}</p><strong>{option?.name}</strong><input value={team.formation??""} onChange={(event)=>updateTeam(teamIndex,{formation:event.target.value||null})} placeholder="Modulo" className="ml-3 min-h-12 rounded-xl border px-3"/><ol className="mt-4 space-y-3">{team.players.map((player,playerIndex)=><SlotEditor key={playerIndex} player={player} societyId={team.societyId!} roster={option?.roster??[]} leaguePlayers={option?.leaguePlayers??[]} onChange={(slot)=>{const players=team.players.map((item,index)=>index===playerIndex?{...item,slot,playerId:slot?.source==="roster"?slot.rosterPlayerId:null,status:slot?"recognized":"unrecognized"} as PlayerMatch:item);updateTeam(teamIndex,{players,captainId:null,viceCaptainId:null});}}/>)}</ol><div className="mt-4 grid gap-3 sm:grid-cols-2"><Leader label="Capitano" value={team.captainId} players={team.players} onChange={(captainId)=>updateTeam(teamIndex,{captainId})}/><Leader label="Vicecapitano" value={team.viceCaptainId} players={team.players} onChange={(viceCaptainId)=>updateTeam(teamIndex,{viceCaptainId})}/></div></article>;})}<button type="button" disabled={confirmDisabled} onClick={confirm} className="min-h-12 w-full rounded-xl bg-emerald-700 text-white disabled:bg-slate-300">{saving?"Salvataggio…":"Conferma formazioni, C e VC"}</button></section>}
  </div>;
}

function SlotEditor({ player, societyId, roster, leaguePlayers, onChange }: { player: PlayerMatch; societyId: number; roster: RosterPlayer[]; leaguePlayers: RosterPlayer[]; onChange: (slot: LineupSlot | null) => void }) {
  const slot=player.slot; const selected=slot?.source==="roster"?leaguePlayers.find((item)=>item.id===slot.rosterPlayerId):null; const outside=selected&&selected.societyId!==societyId;
  return <li className="rounded-xl bg-slate-50 p-3"><strong className="block">{player.detectedName||"Non letto"}</strong><span className="text-xs">{slot?"✓ Confermato":statusLabel[player.status]}</span><div className="mt-2 grid gap-2 sm:grid-cols-3"><label>Giocatore della rosa<select value={selected&&!outside?selected.id:""} onChange={(event)=>onChange(event.target.value?{source:"roster",rosterPlayerId:Number(event.target.value)}:null)} className="block min-h-12 w-full"><option value="">Scegli dalla rosa</option>{roster.map((item)=><option key={item.id} value={item.id}>{item.role} · {item.name}</option>)}</select></label><label>Cerca fuori rosa<select value={outside?selected.id:""} onChange={(event)=>onChange(event.target.value?{source:"roster",rosterPlayerId:Number(event.target.value),overrideConfirmed:false}:null)} className="block min-h-12 w-full"><option value="">Cerca manualmente</option>{leaguePlayers.filter((item)=>item.societyId!==societyId).map((item)=><option key={item.id} value={item.id}>{item.role} · {item.name} · {item.societyName}{item.realTeam?` · ${item.realTeam}`:""}</option>)}</select></label><button type="button" onClick={()=>onChange({source:"manual",player:"",role:"P",overrideConfirmed:false})} className="min-h-12 rounded-xl border">Inserisci giocatore manuale</button></div>{outside&&<Override checked={Boolean(slot?.overrideConfirmed)} label="FUORI ROSA — CONFERMA MANUALE" onChange={(checked)=>onChange({...slot!,overrideConfirmed:checked})}/>} {slot?.source==="manual"&&<div className="mt-2 rounded-xl border border-rose-300 p-3"><p className="font-black text-rose-800">GIOCATORE MANUALE — NON PRESENTE NELLE ROSE</p><input maxLength={120} value={slot.player} onChange={(event)=>onChange({...slot,player:event.target.value})} placeholder="Nome giocatore" className="mt-2 min-h-12 w-full border px-3"/><select value={slot.role} onChange={(event)=>onChange({...slot,role:event.target.value as "P"|"D"|"C"|"A"})} className="mt-2 min-h-12 w-full">{["P","D","C","A"].map((role)=><option key={role}>{role}</option>)}</select><Override checked={Boolean(slot.overrideConfirmed)} label="Confermo l'inserimento manuale" onChange={(checked)=>onChange({...slot,overrideConfirmed:checked})}/></div>}</li>;
}
function Override({checked,label,onChange}:{checked:boolean;label:string;onChange:(checked:boolean)=>void}){return <label className="mt-2 flex gap-2 font-black text-amber-800"><input type="checkbox" checked={checked} onChange={(event)=>onChange(event.target.checked)}/>{label}</label>;}
function Leader({label,value,players,onChange}:{label:string;value:number|null;players:PlayerMatch[];onChange:(value:number|null)=>void}){return <label>{label}<select value={value??""} onChange={(event)=>onChange(Number(event.target.value)||null)} className="min-h-12 w-full min-w-0"><option value="">Scegli tra gli 11 titolari</option>{players.map((player,index)=><option key={index} value={index+1} disabled={!player.slot}>{index+1}. {player.slot?.source==="manual"?player.slot.player:player.detectedName}</option>)}</select></label>;}
