-- Incremental schema only. This migration is not executed by local import tools.

begin;

create table public.riposi_competizione (
  id bigint generated by default as identity primary key,
  edizione_competizione_id bigint not null references public.edizioni_competizioni(id),
  giornata_lega smallint not null,
  giornata_serie_a smallint null,
  societa_id smallint not null references public.societa(id),
  fase text null,
  girone text null,
  raggruppamento text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint riposi_competizione_giornata_lega_positiva
    check (giornata_lega > 0),
  constraint riposi_competizione_giornata_serie_a_positiva
    check (giornata_serie_a is null or giornata_serie_a > 0),
  constraint riposi_competizione_edizione_giornata_societa_unique
    unique (edizione_competizione_id, giornata_lega, societa_id)
);

create index riposi_competizione_edizione_giornata_idx
  on public.riposi_competizione (edizione_competizione_id, giornata_lega);

create or replace function public.set_riposi_competizione_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger riposi_competizione_set_updated_at
before update on public.riposi_competizione
for each row execute function public.set_riposi_competizione_updated_at();

alter table public.riposi_competizione enable row level security;

revoke all on public.riposi_competizione from anon, authenticated;
grant select on public.riposi_competizione to anon, authenticated;

create policy riposi_competizione_public_read
on public.riposi_competizione for select
to anon, authenticated
using (true);

commit;
