-- Incremental schema only. This migration is not executed by local import tools.

begin;

create table public.partite (
  id bigint generated by default as identity primary key,
  edizione_competizione_id bigint not null references public.edizioni_competizioni(id),
  giornata_lega smallint not null,
  giornata_serie_a smallint null,
  societa_casa_id smallint not null references public.societa(id),
  societa_trasferta_id smallint not null references public.societa(id),
  fantapunti_casa numeric(6,2) null,
  fantapunti_trasferta numeric(6,2) null,
  gol_casa smallint null,
  gol_trasferta smallint null,
  stato text not null default 'programmata',
  fonte_importazione text null,
  import_batch_id uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint partite_stato_ammesso
    check (stato in ('programmata', 'calcolata', 'rinviata', 'annullata')),
  constraint partite_giornata_lega_positiva
    check (giornata_lega > 0),
  constraint partite_giornata_serie_a_positiva
    check (giornata_serie_a is null or giornata_serie_a > 0),
  constraint partite_societa_distinte
    check (societa_casa_id <> societa_trasferta_id),
  constraint partite_fantapunti_casa_non_negativi
    check (fantapunti_casa is null or fantapunti_casa >= 0),
  constraint partite_fantapunti_trasferta_non_negativi
    check (fantapunti_trasferta is null or fantapunti_trasferta >= 0),
  constraint partite_gol_casa_non_negativi
    check (gol_casa is null or gol_casa >= 0),
  constraint partite_gol_trasferta_non_negativi
    check (gol_trasferta is null or gol_trasferta >= 0),
  constraint partite_edizione_giornata_squadre_unique
    unique (
      edizione_competizione_id,
      giornata_lega,
      societa_casa_id,
      societa_trasferta_id
    )
);

create index partite_edizione_giornata_idx
  on public.partite (edizione_competizione_id, giornata_lega);

create or replace function public.set_partite_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger partite_set_updated_at
before update on public.partite
for each row execute function public.set_partite_updated_at();

alter table public.partite enable row level security;

revoke all on public.partite from anon, authenticated;
grant select on public.partite to anon, authenticated;

create policy partite_public_read
on public.partite for select
to anon, authenticated
using (true);

commit;
