begin;

create table public.stagioni (
  id smallint generated by default as identity primary key,
  codice text not null unique,
  anno_inizio smallint not null unique,
  anno_fine smallint not null unique,
  nome text not null,
  attiva boolean not null default false,
  data_inizio date null,
  data_fine date null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint stagioni_anni_consecutivi
    check (anno_fine = anno_inizio + 1),
  constraint stagioni_codice_formato
    check (codice ~ '^[0-9]{4}/[0-9]{2}$')
);

create unique index stagioni_una_sola_attiva_idx
  on public.stagioni (attiva)
  where attiva = true;

create or replace function public.set_stagioni_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger stagioni_set_updated_at
before update on public.stagioni
for each row execute function public.set_stagioni_updated_at();

alter table public.stagioni enable row level security;

revoke all on public.stagioni from anon, authenticated;
grant select on public.stagioni to anon, authenticated;

create policy stagioni_public_read
on public.stagioni for select
to anon, authenticated
using (true);

insert into public.stagioni (
  codice,
  anno_inizio,
  anno_fine,
  nome,
  attiva,
  data_inizio,
  data_fine
) values
  ('2023/24', 2023, 2024, '2023/24', false, null, null),
  ('2024/25', 2024, 2025, '2024/25', false, null, null),
  ('2025/26', 2025, 2026, '2025/26', false, null, null),
  ('2026/27', 2026, 2027, '2026/27', true, null, null);

commit;
