begin;

create table public.competizioni (
  id smallint generated by default as identity primary key,
  codice text not null unique,
  nome text not null,
  tipo text not null,
  divisione_riferimento text null,
  livello smallint null,
  attiva boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint competizioni_tipo_ammesso
    check (tipo in ('campionato', 'coppa_nazionale', 'coppa_europea'))
);

create table public.edizioni_competizioni (
  id bigint generated by default as identity primary key,
  competizione_id smallint not null references public.competizioni(id),
  stagione_id smallint not null references public.stagioni(id),
  nome_edizione text not null,
  formato text null,
  numero_squadre smallint null,
  numero_giornate smallint null,
  stato text not null default 'programmata',
  data_inizio date null,
  data_fine date null,
  attiva boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint edizioni_competizioni_stato_ammesso
    check (stato in ('programmata', 'in_corso', 'conclusa', 'annullata')),
  constraint edizioni_competizioni_competizione_stagione_unique
    unique (competizione_id, stagione_id)
);

create or replace function public.set_competizioni_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger competizioni_set_updated_at
before update on public.competizioni
for each row execute function public.set_competizioni_updated_at();

create or replace function public.set_edizioni_competizioni_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger edizioni_competizioni_set_updated_at
before update on public.edizioni_competizioni
for each row execute function public.set_edizioni_competizioni_updated_at();

alter table public.competizioni enable row level security;
alter table public.edizioni_competizioni enable row level security;

revoke all on public.competizioni from anon, authenticated;
revoke all on public.edizioni_competizioni from anon, authenticated;
grant select on public.competizioni to anon, authenticated;
grant select on public.edizioni_competizioni to anon, authenticated;

create policy competizioni_public_read
on public.competizioni for select
to anon, authenticated
using (true);

create policy edizioni_competizioni_public_read
on public.edizioni_competizioni for select
to anon, authenticated
using (true);

insert into public.competizioni (
  codice,
  nome,
  tipo,
  divisione_riferimento,
  livello
) values
  ('serie-a', 'Serie A', 'campionato', 'Serie A', 1),
  ('serie-b', 'Serie B', 'campionato', 'Serie B', 2),
  ('serie-c-girone-a', 'Serie C Girone A', 'campionato', 'Serie C Girone A', 3),
  ('serie-c-girone-b', 'Serie C Girone B', 'campionato', 'Serie C Girone B', 3),
  ('serie-c-girone-c', 'Serie C Girone C', 'campionato', 'Serie C Girone C', 3),
  ('coppa-fanta-20', 'Coppa Fanta a 20', 'coppa_nazionale', null, null),
  ('champions-league-serie-a', 'Champions League Serie A', 'coppa_europea', 'Serie A', 1),
  ('europa-league-serie-a', 'Europa League Serie A', 'coppa_europea', 'Serie A', 1),
  ('conference-league-serie-a', 'Conference League Serie A', 'coppa_europea', 'Serie A', 1),
  ('champions-league-serie-b', 'Champions League Serie B', 'coppa_europea', 'Serie B', 2),
  ('europa-league-serie-b', 'Europa League Serie B', 'coppa_europea', 'Serie B', 2),
  ('conference-league-serie-b', 'Conference League Serie B', 'coppa_europea', 'Serie B', 2),
  ('champions-league-serie-c-girone-a', 'Champions League Serie C Girone A', 'coppa_europea', 'Serie C Girone A', 3),
  ('europa-league-serie-c-girone-a', 'Europa League Serie C Girone A', 'coppa_europea', 'Serie C Girone A', 3),
  ('conference-league-serie-c-girone-a', 'Conference League Serie C Girone A', 'coppa_europea', 'Serie C Girone A', 3),
  ('champions-league-serie-c-girone-b', 'Champions League Serie C Girone B', 'coppa_europea', 'Serie C Girone B', 3),
  ('europa-league-serie-c-girone-b', 'Europa League Serie C Girone B', 'coppa_europea', 'Serie C Girone B', 3),
  ('conference-league-serie-c-girone-b', 'Conference League Serie C Girone B', 'coppa_europea', 'Serie C Girone B', 3),
  ('champions-league-serie-c-girone-c', 'Champions League Serie C Girone C', 'coppa_europea', 'Serie C Girone C', 3),
  ('europa-league-serie-c-girone-c', 'Europa League Serie C Girone C', 'coppa_europea', 'Serie C Girone C', 3),
  ('conference-league-serie-c-girone-c', 'Conference League Serie C Girone C', 'coppa_europea', 'Serie C Girone C', 3);

with edizioni (codice_competizione, codice_stagione, stato) as (
  values
    ('serie-a', '2023/24', 'conclusa'),
    ('champions-league-serie-a', '2023/24', 'conclusa'),
    ('europa-league-serie-a', '2023/24', 'conclusa'),
    ('conference-league-serie-a', '2023/24', 'conclusa'),
    ('serie-a', '2024/25', 'conclusa'),
    ('serie-b', '2024/25', 'conclusa'),
    ('coppa-fanta-20', '2024/25', 'conclusa'),
    ('champions-league-serie-a', '2024/25', 'conclusa'),
    ('europa-league-serie-a', '2024/25', 'conclusa'),
    ('conference-league-serie-a', '2024/25', 'conclusa'),
    ('champions-league-serie-b', '2024/25', 'conclusa'),
    ('europa-league-serie-b', '2024/25', 'conclusa'),
    ('conference-league-serie-b', '2024/25', 'conclusa'),
    ('serie-a', '2025/26', 'conclusa'),
    ('serie-b', '2025/26', 'conclusa'),
    ('serie-c-girone-a', '2025/26', 'conclusa'),
    ('serie-c-girone-b', '2025/26', 'conclusa'),
    ('serie-c-girone-c', '2025/26', 'conclusa'),
    ('coppa-fanta-20', '2025/26', 'conclusa'),
    ('champions-league-serie-a', '2025/26', 'conclusa'),
    ('europa-league-serie-a', '2025/26', 'conclusa'),
    ('conference-league-serie-a', '2025/26', 'conclusa'),
    ('champions-league-serie-b', '2025/26', 'conclusa'),
    ('europa-league-serie-b', '2025/26', 'conclusa'),
    ('conference-league-serie-b', '2025/26', 'conclusa'),
    ('champions-league-serie-c-girone-a', '2025/26', 'conclusa'),
    ('europa-league-serie-c-girone-a', '2025/26', 'conclusa'),
    ('conference-league-serie-c-girone-a', '2025/26', 'conclusa'),
    ('champions-league-serie-c-girone-b', '2025/26', 'conclusa'),
    ('europa-league-serie-c-girone-b', '2025/26', 'conclusa'),
    ('conference-league-serie-c-girone-b', '2025/26', 'conclusa'),
    ('champions-league-serie-c-girone-c', '2025/26', 'conclusa'),
    ('europa-league-serie-c-girone-c', '2025/26', 'conclusa'),
    ('conference-league-serie-c-girone-c', '2025/26', 'conclusa'),
    ('serie-a', '2026/27', 'programmata'),
    ('serie-b', '2026/27', 'programmata'),
    ('serie-c-girone-a', '2026/27', 'programmata'),
    ('serie-c-girone-b', '2026/27', 'programmata'),
    ('serie-c-girone-c', '2026/27', 'programmata'),
    ('coppa-fanta-20', '2026/27', 'programmata'),
    ('champions-league-serie-a', '2026/27', 'programmata'),
    ('europa-league-serie-a', '2026/27', 'programmata'),
    ('conference-league-serie-a', '2026/27', 'programmata'),
    ('champions-league-serie-b', '2026/27', 'programmata'),
    ('europa-league-serie-b', '2026/27', 'programmata'),
    ('conference-league-serie-b', '2026/27', 'programmata'),
    ('champions-league-serie-c-girone-a', '2026/27', 'programmata'),
    ('europa-league-serie-c-girone-a', '2026/27', 'programmata'),
    ('conference-league-serie-c-girone-a', '2026/27', 'programmata'),
    ('champions-league-serie-c-girone-b', '2026/27', 'programmata'),
    ('europa-league-serie-c-girone-b', '2026/27', 'programmata'),
    ('conference-league-serie-c-girone-b', '2026/27', 'programmata'),
    ('champions-league-serie-c-girone-c', '2026/27', 'programmata'),
    ('europa-league-serie-c-girone-c', '2026/27', 'programmata'),
    ('conference-league-serie-c-girone-c', '2026/27', 'programmata')
)
insert into public.edizioni_competizioni (
  competizione_id,
  stagione_id,
  nome_edizione,
  formato,
  numero_squadre,
  numero_giornate,
  stato,
  data_inizio,
  data_fine
)
select
  c.id,
  s.id,
  c.nome || ' ' || s.codice,
  null,
  null,
  null,
  e.stato,
  null,
  null
from edizioni e
join public.competizioni c on c.codice = e.codice_competizione
join public.stagioni s on s.codice = e.codice_stagione;

commit;
