-- FantaBet core: versioned V1 rounds, deadline enforcement and derived scores.
-- Apply only after 202608070001_account_profiles.sql and 202608050001_partite.sql.
begin;

create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.fantabet_rounds (
  id bigint generated by default as identity primary key,
  stagione_id smallint not null references public.stagioni(id),
  numero_giornata smallint not null,
  opens_at timestamptz not null,
  deadline_at timestamptz not null,
  status text not null default 'bozza',
  round_type text not null default 'STANDARD',
  rules_version smallint not null default 1,
  required_predictions smallint not null default 5,
  perfect_multiplier smallint not null default 2,
  consistency_block_size smallint not null default 5,
  consistency_bonus_points smallint not null default 10,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fantabet_rounds_numero_giornata_positivo check (numero_giornata > 0),
  constraint fantabet_rounds_intervallo_valido check (opens_at < deadline_at),
  constraint fantabet_rounds_status_ammesso check (status in ('bozza', 'pubblicata', 'chiusa', 'valutata', 'annullata')),
  constraint fantabet_rounds_tipo_non_vuoto check (btrim(round_type) <> ''),
  constraint fantabet_rounds_versione_regole_positiva check (rules_version > 0),
  constraint fantabet_rounds_pronostici_richiesti_positivi check (required_predictions > 0),
  constraint fantabet_rounds_moltiplicatore_valido check (perfect_multiplier >= 1),
  constraint fantabet_rounds_blocco_costanza_positivo check (consistency_block_size > 0),
  constraint fantabet_rounds_bonus_costanza_non_negativo check (consistency_bonus_points >= 0),
  constraint fantabet_rounds_stagione_giornata_unique unique (stagione_id, numero_giornata)
);

create table public.fantabet_bets (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.fantabet_rounds(id) on delete cascade,
  partita_id bigint not null references public.partite(id),
  bet_type text not null,
  points_value smallint not null,
  display_order smallint not null,
  created_at timestamptz not null default now(),
  constraint fantabet_bets_type_non_vuoto check (btrim(bet_type) <> ''),
  constraint fantabet_bets_punti_positivi check (points_value > 0),
  constraint fantabet_bets_ordine_positivo check (display_order > 0),
  constraint fantabet_bets_round_partita_unique unique (round_id, partita_id),
  constraint fantabet_bets_round_ordine_unique unique (round_id, display_order)
);

create table public.fantabet_predictions (
  id bigint generated by default as identity primary key,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  bet_id bigint not null references public.fantabet_bets(id) on delete cascade,
  scelta text not null,
  exact_home smallint null,
  exact_away smallint null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint fantabet_predictions_scelta_ammessa check (scelta in ('1', 'X', '2', 'UNDER', 'OVER', 'ESATTO')),
  constraint fantabet_predictions_exact_home_non_negativo check (exact_home is null or exact_home >= 0),
  constraint fantabet_predictions_exact_away_non_negativo check (exact_away is null or exact_away >= 0),
  constraint fantabet_predictions_profile_bet_unique unique (profile_id, bet_id)
);

create index fantabet_bets_round_idx on public.fantabet_bets (round_id);
create index fantabet_bets_partita_idx on public.fantabet_bets (partita_id);
create index fantabet_predictions_profile_idx on public.fantabet_predictions (profile_id);
create index fantabet_predictions_bet_idx on public.fantabet_predictions (bet_id);

create or replace function public.set_fantabet_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at := statement_timestamp();
  return new;
end;
$$;

create trigger fantabet_rounds_set_updated_at
before update on public.fantabet_rounds
for each row execute function public.set_fantabet_updated_at();

create trigger fantabet_predictions_set_updated_at
before update on public.fantabet_predictions
for each row execute function public.set_fantabet_updated_at();

create or replace function public.validate_fantabet_round_publication()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  total_bets integer;
  valid_bets integer;
  distinct_matches integer;
  distinct_orders integer;
begin
  if tg_op = 'UPDATE' then
    if old.status <> 'bozza' and (
      new.stagione_id is distinct from old.stagione_id
      or new.numero_giornata is distinct from old.numero_giornata
      or new.opens_at is distinct from old.opens_at
      or new.deadline_at is distinct from old.deadline_at
      or new.round_type is distinct from old.round_type
      or new.rules_version is distinct from old.rules_version
      or new.required_predictions is distinct from old.required_predictions
      or new.perfect_multiplier is distinct from old.perfect_multiplier
      or new.consistency_block_size is distinct from old.consistency_block_size
      or new.consistency_bonus_points is distinct from old.consistency_bonus_points
    ) then
      raise exception 'FANTABET_CONFIGURAZIONE_PUBBLICATA_IMMUTABILE' using errcode = '55000';
    end if;

    if old.status <> new.status and not (
      (old.status = 'bozza' and new.status in ('pubblicata', 'annullata'))
      or (old.status = 'pubblicata' and new.status in ('chiusa', 'annullata'))
      or (old.status = 'chiusa' and new.status in ('valutata', 'annullata'))
    ) then
      raise exception 'FANTABET_TRANSIZIONE_STATO_NON_VALIDA' using errcode = '22023';
    end if;
  end if;

  if new.status = 'pubblicata' and tg_op = 'INSERT' then
    raise exception 'FANTABET_CREARE_PRIMA_LA_BOZZA' using errcode = '23514';
  end if;

  if tg_op = 'UPDATE' and new.status = 'pubblicata' and old.status <> 'pubblicata' then
    if new.deadline_at <= statement_timestamp() then
      raise exception 'FANTABET_DEADLINE_GIA_TRASCORSA' using errcode = '22023';
    end if;

    if new.round_type <> 'STANDARD' or new.rules_version <> 1
      or new.required_predictions <> 5 or new.perfect_multiplier <> 2
      or new.consistency_block_size <> 5 or new.consistency_bonus_points <> 10
    then
      raise exception 'FANTABET_REGOLE_NON_SUPPORTATE' using errcode = '22023';
    end if;

    select
      count(*),
      count(*) filter (where
        (bet_type = '1X2' and points_value = 3)
        or (bet_type = 'UNDER_OVER_2_5' and points_value = 1)
        or (bet_type = 'RISULTATO_ESATTO' and points_value = 10)
        or (bet_type = 'FANTAPUNTEGGIO_1X2' and points_value = 2)
      ),
      count(distinct partita_id),
      count(distinct display_order)
    into total_bets, valid_bets, distinct_matches, distinct_orders
    from public.fantabet_bets
    where round_id = new.id;

    if total_bets <> 5 or valid_bets <> 5 or distinct_matches <> 5 or distinct_orders <> 5
      or (select count(*) from public.fantabet_bets where round_id = new.id and bet_type = '1X2') <> 2
      or (select count(*) from public.fantabet_bets where round_id = new.id and bet_type = 'UNDER_OVER_2_5') <> 1
      or (select count(*) from public.fantabet_bets where round_id = new.id and bet_type = 'RISULTATO_ESATTO') <> 1
      or (select count(*) from public.fantabet_bets where round_id = new.id and bet_type = 'FANTAPUNTEGGIO_1X2') <> 1
    then
      raise exception 'FANTABET_ROUND_NON_PUBBLICABILE' using errcode = '23514';
    end if;
  end if;
  return new;
end;
$$;

create trigger fantabet_rounds_validate_publication
before insert or update on public.fantabet_rounds
for each row execute function public.validate_fantabet_round_publication();

create or replace function public.protect_published_fantabet_bets()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target_round_id bigint;
  round_status text;
begin
  if tg_op = 'DELETE' then
    target_round_id := old.round_id;
  else
    target_round_id := new.round_id;
  end if;
  select status into round_status from public.fantabet_rounds where id = target_round_id;
  if round_status <> 'bozza' then
    raise exception 'FANTABET_GIOCATE_PUBBLICATE_IMMUTABILI' using errcode = '55000';
  end if;
  if tg_op = 'UPDATE' and new.round_id <> old.round_id then
    raise exception 'FANTABET_ROUND_GIOCATA_IMMUTABILE' using errcode = '55000';
  end if;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create trigger fantabet_bets_protect_published
before insert or update or delete on public.fantabet_bets
for each row execute function public.protect_published_fantabet_bets();

create or replace function public.fantabet_prediction_window_open(p_bet_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.fantabet_bets bet
    join public.fantabet_rounds round on round.id = bet.round_id
    where bet.id = p_bet_id
      and round.status = 'pubblicata'
      and statement_timestamp() >= round.opens_at
      and statement_timestamp() < round.deadline_at
  );
$$;

create or replace function public.validate_fantabet_prediction()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
declare
  target_type text;
begin
  if tg_op = 'UPDATE' and (new.profile_id <> old.profile_id or new.bet_id <> old.bet_id) then
    raise exception 'FANTABET_IDENTITA_PRONOSTICO_IMMUTABILE' using errcode = '55000';
  end if;
  if not public.fantabet_prediction_window_open(new.bet_id) then
    raise exception 'FANTABET_PRONOSTICI_CHIUSI' using errcode = '42501';
  end if;

  select bet_type into target_type from public.fantabet_bets where id = new.bet_id;
  if target_type in ('1X2', 'FANTAPUNTEGGIO_1X2') then
    if new.scelta not in ('1', 'X', '2') or new.exact_home is not null or new.exact_away is not null then
      raise exception 'FANTABET_PRONOSTICO_NON_VALIDO' using errcode = '22023';
    end if;
  elsif target_type = 'UNDER_OVER_2_5' then
    if new.scelta not in ('UNDER', 'OVER') or new.exact_home is not null or new.exact_away is not null then
      raise exception 'FANTABET_PRONOSTICO_NON_VALIDO' using errcode = '22023';
    end if;
  elsif target_type = 'RISULTATO_ESATTO' then
    if new.scelta <> 'ESATTO' or new.exact_home is null or new.exact_away is null then
      raise exception 'FANTABET_PRONOSTICO_NON_VALIDO' using errcode = '22023';
    end if;
  else
    raise exception 'FANTABET_GIOCATA_NON_TROVATA' using errcode = 'P0002';
  end if;
  return new;
end;
$$;

create trigger fantabet_predictions_validate
before insert or update on public.fantabet_predictions
for each row execute function public.validate_fantabet_prediction();

create view private.fantabet_bet_results as
select
  bet.id as bet_id,
  bet.round_id,
  bet.bet_type,
  bet.points_value,
  case
    when match.stato <> 'calcolata' then false
    when bet.bet_type = 'FANTAPUNTEGGIO_1X2' then match.fantapunti_casa is not null and match.fantapunti_trasferta is not null
    else match.gol_casa is not null and match.gol_trasferta is not null
  end as resolvable,
  case
    when bet.bet_type = '1X2' and match.gol_casa > match.gol_trasferta then '1'
    when bet.bet_type = '1X2' and match.gol_casa = match.gol_trasferta then 'X'
    when bet.bet_type = '1X2' and match.gol_casa < match.gol_trasferta then '2'
    when bet.bet_type = 'UNDER_OVER_2_5' and match.gol_casa + match.gol_trasferta <= 2 then 'UNDER'
    when bet.bet_type = 'UNDER_OVER_2_5' and match.gol_casa + match.gol_trasferta >= 3 then 'OVER'
    when bet.bet_type = 'FANTAPUNTEGGIO_1X2' and match.fantapunti_casa > match.fantapunti_trasferta then '1'
    when bet.bet_type = 'FANTAPUNTEGGIO_1X2' and match.fantapunti_casa = match.fantapunti_trasferta then 'X'
    when bet.bet_type = 'FANTAPUNTEGGIO_1X2' and match.fantapunti_casa < match.fantapunti_trasferta then '2'
    when bet.bet_type = 'RISULTATO_ESATTO' then 'ESATTO'
    else null
  end as result_choice,
  match.gol_casa,
  match.gol_trasferta
from public.fantabet_bets bet
join public.partite match on match.id = bet.partita_id;

create view private.fantabet_round_evaluation as
select result.round_id, count(*) = round.required_predictions and bool_and(result.resolvable) as fully_evaluable
from private.fantabet_bet_results result
join public.fantabet_rounds round on round.id = result.round_id
where round.status in ('pubblicata', 'chiusa', 'valutata')
group by result.round_id, round.required_predictions;

create view private.fantabet_prediction_results as
select
  prediction.profile_id,
  result.round_id,
  prediction.bet_id,
  case
    when not result.resolvable then null
    when result.bet_type = 'RISULTATO_ESATTO' then prediction.exact_home = result.gol_casa and prediction.exact_away = result.gol_trasferta
    else prediction.scelta = result.result_choice
  end as correct,
  case
    when not result.resolvable then null
    when result.bet_type = 'RISULTATO_ESATTO' and prediction.exact_home = result.gol_casa and prediction.exact_away = result.gol_trasferta then result.points_value
    when result.bet_type <> 'RISULTATO_ESATTO' and prediction.scelta = result.result_choice then result.points_value
    else 0
  end as earned_points
from public.fantabet_predictions prediction
join private.fantabet_bet_results result on result.bet_id = prediction.bet_id;

revoke all on private.fantabet_bet_results from public, anon, authenticated;
revoke all on private.fantabet_round_evaluation from public, anon, authenticated;
revoke all on private.fantabet_prediction_results from public, anon, authenticated;

create or replace function public.fantabet_round_is_evaluable(p_round_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce((select fully_evaluable from private.fantabet_round_evaluation where round_id = p_round_id), false);
$$;

create or replace function public.fantabet_global_leaderboard()
returns table (
  profile_id uuid,
  username text,
  punti_pronostici bigint,
  punti_bonus_costanza bigint,
  punti_totali bigint,
  giornate_giocate bigint,
  pronostici_corretti bigint,
  schedine_perfette bigint,
  streak_attuale bigint,
  posizione bigint
)
language sql
stable
security definer
set search_path = ''
as $$
  with complete_rounds as (
    select round_id from private.fantabet_round_evaluation where fully_evaluable
  ),
  scored_slips as (
    select
      result.profile_id,
      result.round_id,
      round.required_predictions,
      round.perfect_multiplier,
      count(*) as prediction_count,
      count(*) filter (where result.correct) as correct_count,
      coalesce(sum(result.earned_points), 0)::bigint as base_points
    from private.fantabet_prediction_results result
    join complete_rounds complete on complete.round_id = result.round_id
    join public.fantabet_rounds round on round.id = result.round_id
    group by result.profile_id, result.round_id, round.required_predictions, round.perfect_multiplier
  ),
  prediction_totals as (
    select
      profile.id as profile_id,
      sum(case when score.prediction_count = score.required_predictions and score.correct_count = score.required_predictions then score.base_points * score.perfect_multiplier else score.base_points end)::bigint as punti_totali,
      count(*)::bigint as giornate_giocate,
      sum(score.correct_count)::bigint as pronostici_corretti,
      count(*) filter (where score.prediction_count = score.required_predictions and score.correct_count = score.required_predictions)::bigint as schedine_perfette
    from scored_slips score
    join public.profiles profile on profile.id = score.profile_id
    where score.prediction_count = score.required_predictions
    group by profile.id
  ),
  expired_rounds as (
    -- Annullate rounds do not exist for participation, streak, bonus or scoring.
    select round.id, round.deadline_at, round.required_predictions,
      round.consistency_block_size, round.consistency_bonus_points
    from public.fantabet_rounds round
    where round.status in ('pubblicata', 'chiusa', 'valutata')
      and round.deadline_at <= statement_timestamp()
  ),
  participation_counts as (
    select prediction.profile_id, bet.round_id, round.required_predictions,
      count(*)::integer as prediction_count
    from public.fantabet_predictions prediction
    join public.fantabet_bets bet on bet.id = prediction.bet_id
    join expired_rounds round on round.id = bet.round_id
    group by prediction.profile_id, bet.round_id, round.required_predictions
  ),
  participating_profiles as (
    select distinct profile_id
    from participation_counts
    where prediction_count = required_predictions
  ),
  participation_timeline as (
    select
      profile.id as profile_id,
      round.id as round_id,
      round.deadline_at,
      round.consistency_block_size,
      round.consistency_bonus_points,
      coalesce(participation.prediction_count, 0) = round.required_predictions as complete,
      sum(case when coalesce(participation.prediction_count, 0) = round.required_predictions then 0 else 1 end) over (
        partition by profile.id order by round.deadline_at, round.id
      ) as streak_group,
      row_number() over (
        partition by profile.id order by round.deadline_at desc, round.id desc
      ) as reverse_order
    from participating_profiles participant
    join public.profiles profile on profile.id = participant.profile_id
    join expired_rounds round on round.deadline_at >= profile.created_at
    left join participation_counts participation
      on participation.profile_id = profile.id and participation.round_id = round.id
  ),
  streak_positions as (
    select timeline.*,
      row_number() over (
        partition by timeline.profile_id, timeline.streak_group
        order by timeline.deadline_at, timeline.round_id
      )::bigint as streak_position
    from participation_timeline timeline
    where timeline.complete
  ),
  consistency_totals as (
    select
      profile_id,
      sum(case when mod(streak_position, consistency_block_size) = 0 then consistency_bonus_points else 0 end)::bigint as punti_bonus_costanza
    from streak_positions
    group by profile_id
  ),
  current_streaks as (
    select
      timeline.profile_id,
      case
        when bool_or(timeline.complete and timeline.reverse_order = 1)
          then coalesce(max(streak_row.streak_position) filter (where timeline.reverse_order = 1), 0)
        else 0
      end::bigint as streak_attuale
    from participation_timeline timeline
    left join streak_positions streak_row
      on streak_row.profile_id = timeline.profile_id and streak_row.round_id = timeline.round_id
    group by timeline.profile_id
  ),
  totals as (
    select
      profile.id as profile_id,
      profile.username,
      profile.username_normalizzato,
      coalesce(prediction.punti_totali, 0)::bigint as punti_pronostici,
      coalesce(consistency.punti_bonus_costanza, 0)::bigint as punti_bonus_costanza,
      (coalesce(prediction.punti_totali, 0) + coalesce(consistency.punti_bonus_costanza, 0))::bigint as punti_totali,
      coalesce(prediction.giornate_giocate, 0)::bigint as giornate_giocate,
      coalesce(prediction.pronostici_corretti, 0)::bigint as pronostici_corretti,
      coalesce(prediction.schedine_perfette, 0)::bigint as schedine_perfette,
      coalesce(streak.streak_attuale, 0)::bigint as streak_attuale
    from participating_profiles participant
    join public.profiles profile on profile.id = participant.profile_id
    left join prediction_totals prediction on prediction.profile_id = profile.id
    left join consistency_totals consistency on consistency.profile_id = profile.id
    left join current_streaks streak on streak.profile_id = profile.id
  )
  select
    totals.profile_id,
    totals.username,
    totals.punti_pronostici,
    totals.punti_bonus_costanza,
    totals.punti_totali,
    totals.giornate_giocate,
    totals.pronostici_corretti,
    totals.schedine_perfette,
    totals.streak_attuale,
    row_number() over (
      order by totals.punti_totali desc, totals.schedine_perfette desc,
        totals.pronostici_corretti desc, totals.username_normalizzato asc, totals.profile_id asc
    )::bigint as posizione
  from totals
  order by posizione;
$$;

alter table public.fantabet_rounds enable row level security;
alter table public.fantabet_bets enable row level security;
alter table public.fantabet_predictions enable row level security;

revoke all on public.fantabet_rounds from public, anon, authenticated;
revoke all on public.fantabet_bets from public, anon, authenticated;
revoke all on public.fantabet_predictions from public, anon, authenticated;
revoke all on function public.set_fantabet_updated_at() from public, anon, authenticated;
revoke all on function public.validate_fantabet_round_publication() from public, anon, authenticated;
revoke all on function public.protect_published_fantabet_bets() from public, anon, authenticated;
revoke all on function public.fantabet_prediction_window_open(bigint) from public, anon, authenticated;
revoke all on function public.validate_fantabet_prediction() from public, anon, authenticated;
revoke all on function public.fantabet_round_is_evaluable(bigint) from public, anon, authenticated;
revoke all on function public.fantabet_global_leaderboard() from public, anon, authenticated;

grant select on public.fantabet_rounds, public.fantabet_bets to anon, authenticated;
grant select, insert, update on public.fantabet_predictions to authenticated;
grant usage, select on sequence public.fantabet_predictions_id_seq to authenticated;
grant execute on function public.fantabet_prediction_window_open(bigint) to authenticated;
grant execute on function public.fantabet_global_leaderboard() to anon, authenticated;

grant select, insert, update, delete on public.fantabet_rounds, public.fantabet_bets, public.fantabet_predictions to service_role;
grant usage, select on sequence public.fantabet_rounds_id_seq, public.fantabet_bets_id_seq, public.fantabet_predictions_id_seq to service_role;
grant execute on function public.fantabet_round_is_evaluable(bigint) to service_role;
grant execute on function public.fantabet_global_leaderboard() to service_role;

create policy fantabet_rounds_public_read
on public.fantabet_rounds for select
to anon, authenticated
using (status in ('pubblicata', 'chiusa', 'valutata'));

create policy fantabet_bets_public_read
on public.fantabet_bets for select
to anon, authenticated
using (exists (
  select 1 from public.fantabet_rounds round
  where round.id = round_id and round.status in ('pubblicata', 'chiusa', 'valutata')
));

create policy fantabet_predictions_read_own
on public.fantabet_predictions for select
to authenticated
using ((select auth.uid()) is not null and (select auth.uid()) = profile_id);

create policy fantabet_predictions_insert_own_before_deadline
on public.fantabet_predictions for insert
to authenticated
with check (
  (select auth.uid()) is not null
  and (select auth.uid()) = profile_id
  and public.fantabet_prediction_window_open(bet_id)
);

create policy fantabet_predictions_update_own_before_deadline
on public.fantabet_predictions for update
to authenticated
using (
  (select auth.uid()) is not null
  and (select auth.uid()) = profile_id
  and public.fantabet_prediction_window_open(bet_id)
)
with check (
  (select auth.uid()) is not null
  and (select auth.uid()) = profile_id
  and public.fantabet_prediction_window_open(bet_id)
);

commit;
