"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useDeferredValue, useEffect, useLayoutEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { CALENDAR_UNAVAILABLE_MESSAGE } from "@/lib/competition-calendar";
import ScheduledMatchStatus from "../components/ScheduledMatchStatus";
import styles from "../campionati-live-preview/championship.module.css";
import { buildCoppaPrototype, coppaStandingsForRange, isCalculatedCoppaMatch, qualificationSeparatorsFor, sortCoppaStandings, type CoppaMatch, type CoppaSortKey, type CoppaStanding, type CoppaTeam } from "./coppa-fanta-fixture";

const days = Array.from({ length: 14 }, (_, index) => index + 1);

export default function CoppaFantaPrototype({ teams, matches: realMatches = [], demo = false, seed = 20260813, initialDay = 1, hasCalendar = false, loadError = false, initialTab = "results" }: { teams: CoppaTeam[]; matches?: CoppaMatch[]; demo?: boolean; seed?: number; initialDay?: number; hasCalendar?: boolean; loadError?: boolean; initialTab?: "results" | "table" }) {
  const demoMatches = useMemo(() => demo ? buildCoppaPrototype(teams, seed).matches : [], [demo, teams, seed]);
  const sourceMatches = demo ? demoMatches : realMatches;
  const qualificationSeparators = qualificationSeparatorsFor(sourceMatches);
  const [day, setDay] = useState(initialDay); const [tab, setTab] = useState<"results" | "table">(initialTab);
  const [matchSearch, setMatchSearch] = useState(""); const [standingSearch, setStandingSearch] = useState(""); const [modal, setModal] = useState(false);
  const modalOpener = useRef<HTMLButtonElement>(null);
  const normalizedMatchSearch = matchSearch.trim().toLocaleLowerCase("it"); const normalizedStandingSearch = standingSearch.trim().toLocaleLowerCase("it");
  const matches = sourceMatches.filter((match) => match.day === day && (!normalizedMatchSearch || match.home.name.toLocaleLowerCase("it").includes(normalizedMatchSearch) || match.away.name.toLocaleLowerCase("it").includes(normalizedMatchSearch)));
  const dayStandings = coppaStandingsForRange(teams, sourceMatches, 1, day);
  const searchedStandings = normalizedStandingSearch ? dayStandings.filter((row) => row.name.toLocaleLowerCase("it").includes(normalizedStandingSearch)) : dayStandings;
  const standings = normalizedStandingSearch ? searchedStandings : searchedStandings.slice(0, 20);
  const totals = dayStandings.map((row) => row.totalPoints); const minTotal = Math.min(...totals); const maxTotal = Math.max(...totals);
  const closeModal = useCallback(() => { setModal(false); requestAnimationFrame(() => modalOpener.current?.focus()); }, []);

  return <main className="mx-auto min-h-[70vh] w-full max-w-[1440px] overflow-x-hidden px-3 py-5 sm:px-5 sm:py-10 lg:px-8 lg:py-14">
    <header className="mb-5 min-w-0 border-b border-slate-200 pb-5 sm:mb-8"><p className="section-eyebrow">Risultati e classifiche</p><h1 className="font-onder-title mt-2.5 max-w-full text-[2.15rem] uppercase leading-none tracking-[-.025em] sm:mt-4 sm:text-6xl sm:tracking-normal"><span className="block sm:inline">La Coppa</span><span className="mt-1 block sm:ml-[.22em] sm:mt-0 sm:inline">Fanta a 20</span></h1><p className="mt-3 max-w-2xl text-sm font-semibold text-slate-600 sm:text-base">Coppa Fanta a 20 · fase a girone con 100 società e 14 giornate.</p>{demo && <span className="mt-3 inline-flex rounded-full border border-amber-300 bg-amber-50 px-3 py-1 text-[9px] font-black uppercase tracking-wider text-amber-800">Dati demo · nessuna scrittura Supabase</span>}</header>
    {!hasCalendar && !demo ? <Empty text={loadError ? "Non è stato possibile caricare il calendario ufficiale. Riprova più tardi." : CALENDAR_UNAVAILABLE_MESSAGE} /> : <><div className="grid grid-cols-2 rounded-2xl bg-slate-200 p-1 lg:hidden"><button onClick={() => setTab("results")} className={`min-h-11 rounded-xl font-black ${tab === "results" ? "bg-white text-blue-950" : "text-slate-500"}`}>Risultati</button><button onClick={() => setTab("table")} className={`min-h-11 rounded-xl font-black ${tab === "table" ? "bg-white text-blue-950" : "text-slate-500"}`}>Classifica</button></div>
    <div className="mt-5 lg:grid lg:grid-cols-[minmax(0,1.45fr)_minmax(390px,.85fr)] lg:items-start lg:gap-6">
      <section className={`${tab === "results" ? "block" : "hidden lg:block"} min-w-0 space-y-3`}><div className="flex min-h-[60px] items-end justify-between gap-2"><div><p className="section-eyebrow">Coppa Fanta a 20</p><h2 className="text-2xl font-black uppercase text-blue-950">Risultati</h2></div><div className="lg:hidden"><MatchdaySelector day={day} onChange={setDay} /></div></div><Search value={matchSearch} onChange={setMatchSearch} label="Cerca squadra nelle partite" /><div className="grid gap-2">{matches.map((match) => <article key={match.id} className="grid min-h-16 grid-cols-[minmax(0,1fr)_72px_minmax(0,1fr)] items-center gap-1.5 rounded-[1.15rem] border border-slate-200/80 bg-white px-2 py-2 shadow-sm sm:grid-cols-[minmax(0,1fr)_86px_minmax(0,1fr)] sm:px-3"><Team team={match.home} /><div className="text-center">{isCalculatedCoppaMatch(match) ? <><strong className="block whitespace-nowrap text-xl font-black leading-none text-blue-950">{match.homeGoals} - {match.awayGoals}</strong><span className="mt-1 block whitespace-nowrap text-[10px] font-bold tabular-nums text-slate-500">{formatFantasyScore(match.homeScore)} - {formatFantasyScore(match.awayScore)}</span></> : <ScheduledMatchStatus />}</div><Team team={match.away} reverse /></article>)}{matches.length === 0 && <Empty text="Nessuna partita trovata per questa squadra." />}</div></section>
      <section className={`${tab === "table" ? "block" : "hidden lg:block"} min-w-0 space-y-3 lg:sticky lg:top-24`}><div className="flex min-h-[60px] items-end justify-between gap-2"><div><p className="section-eyebrow">Fase di qualificazione</p><h2 className="text-2xl font-black uppercase text-blue-950">Classifica</h2></div><MatchdaySelector day={day} onChange={setDay} /></div><Search value={standingSearch} onChange={setStandingSearch} label="Cerca squadra in classifica" /><Standings rows={standings} minTotal={minTotal} maxTotal={maxTotal} />{standings.length === 0 && <Empty text="Nessuna società trovata in classifica." />}<button ref={modalOpener} type="button" onClick={() => setModal(true)} className="min-h-12 w-full rounded-2xl bg-blue-950 px-4 text-xs font-black uppercase text-white">Espandi classifica</button></section>
    </div>{modal && <FullStandings teams={teams.slice(0, 100)} matches={sourceMatches} qualificationSeparators={qualificationSeparators} initialDay={day} onClose={closeModal} />}</>}
  </main>;
}

function MatchdaySelector({ day, onChange }: { day: number; onChange: (day: number) => void }) { const index = days.indexOf(day); const [open, setOpen] = useState(false); const root = useRef<HTMLDivElement>(null); const selected = useRef<HTMLButtonElement>(null); useEffect(() => { const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []); useLayoutEffect(() => { if (open) selected.current?.scrollIntoView({ block: "center" }); }, [open]); return <div ref={root} className="relative inline-flex h-11 shrink-0 items-center rounded-xl border border-slate-200/80 bg-white shadow-sm"><button disabled={index <= 0} onClick={() => onChange(days[index - 1])} aria-label="Giornata precedente" className="h-11 w-9 rounded-l-xl text-lg font-black text-blue-950 disabled:opacity-30 sm:w-11">←</button><button aria-haspopup="listbox" aria-expanded={open} aria-label="Seleziona giornata" onClick={() => setOpen((value) => !value)} className="flex h-11 min-w-[92px] items-center justify-center border-x border-slate-200/80 px-2 text-[11px] font-black text-blue-950 sm:min-w-[112px] sm:text-sm">Giornata {day}</button><button disabled={index === days.length - 1} onClick={() => onChange(days[index + 1])} aria-label="Giornata successiva" className="h-11 w-9 rounded-r-xl text-lg font-black text-blue-950 disabled:opacity-30 sm:w-11">→</button>{open && <div role="listbox" className="absolute right-9 top-[calc(100%+.35rem)] z-50 max-h-64 min-w-[150px] overflow-y-auto rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl sm:right-11">{days.map((value) => <button ref={value === day ? selected : undefined} key={value} role="option" aria-selected={value === day} onClick={() => { onChange(value); setOpen(false); }} className={`flex min-h-10 w-full items-center rounded-lg px-3 text-left text-xs font-black ${value === day ? "bg-sky-50 text-blue-950" : "text-slate-600 hover:bg-slate-50"}`}>Giornata {value}</button>)}</div>}</div>; }

function Standings({ rows, minTotal, maxTotal }: { rows: CoppaStanding[]; minTotal: number; maxTotal: number }) { return <div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_12px_30px_rgba(15,23,42,.07)]"><div className="grid grid-cols-[38px_minmax(0,1fr)_40px_58px] items-center gap-1 bg-slate-50 px-2 py-2 text-[9px] font-black uppercase text-slate-400 sm:grid-cols-[44px_minmax(0,1fr)_46px_66px]"><span>Pos.</span><span>Società</span><span className="text-right">PT</span><span className="text-right">PT.tot</span></div>{rows.map((row) => <div key={row.id} className="grid min-h-12 grid-cols-[38px_minmax(0,1fr)_40px_58px] items-center gap-1 border-t border-slate-100 px-2 py-1.5 text-xs sm:grid-cols-[44px_minmax(0,1fr)_46px_66px]"><Position row={row} /><Team team={row} marquee /><strong className="text-right tabular-nums text-blue-950">{row.points}</strong><Total value={row.totalPoints} min={minTotal} max={maxTotal} /></div>)}</div>; }

function FullStandings({ teams, matches, qualificationSeparators, initialDay, onClose }: { teams: CoppaTeam[]; matches: CoppaMatch[]; qualificationSeparators: Map<number, { desktop: string; mobile: string }>; initialDay: number; onClose: () => void }) {
  const [from, setFrom] = useState(1); const [to, setTo] = useState(initialDay);
  const deferredFrom = useDeferredValue(from); const deferredTo = useDeferredValue(to);
  const close = useRef<HTMLButtonElement>(null); const [search, setSearch] = useState(""); const [sort, setSort] = useState<CoppaSortKey>("official"); const [direction, setDirection] = useState<"asc" | "desc">("desc");
  const rows = useMemo(() => coppaStandingsForRange(teams, matches, deferredFrom, deferredTo), [teams, matches, deferredFrom, deferredTo]);
  const totals = rows.map((row) => row.totalPoints); const minTotal = Math.min(...totals); const maxTotal = Math.max(...totals);
  const normalized = search.trim().toLocaleLowerCase("it");
  const filtered = normalized ? rows.filter((row) => row.name.toLocaleLowerCase("it").includes(normalized)) : rows;
  const shown = sortCoppaStandings(filtered, sort, direction);
  const changeSort = (key: CoppaSortKey) => { if (sort === key) setDirection((value) => value === "desc" ? "asc" : "desc"); else { setSort(key); setDirection("desc"); } };
  useEffect(() => { const old = document.body.style.overflow; document.body.style.overflow = "hidden"; close.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape") onClose(); }; addEventListener("keydown", key); return () => { document.body.style.overflow = old; removeEventListener("keydown", key); }; }, [onClose]);
  const headers: Array<[string, CoppaSortKey | null]> = [["POS", "official"], ["SQUADRA", null], ["PT", "points"], ["PT TOT", "totalPoints"], ["V", null], ["P", null], ["S", null], ["GF", "goalsFor"], ["GS", "goalsAgainst"]];
  return <div role="dialog" aria-modal="true" className="fixed inset-0 z-[100] bg-slate-950/65 backdrop-blur-md sm:p-3" onMouseDown={onClose}><div className="mx-auto flex h-full max-w-7xl flex-col overflow-hidden bg-[#f8fbff] sm:rounded-[2rem]" onMouseDown={(event) => event.stopPropagation()}>
    <header className="border-b border-slate-200/80 bg-white p-2.5 sm:p-5"><div className="flex items-center justify-between"><div><p className="section-eyebrow">Coppa Fanta a 20</p><h2 className="text-lg font-black uppercase text-blue-950 sm:text-2xl">Classifica completa</h2></div><button ref={close} onClick={onClose} aria-label="Chiudi classifica" className={`${styles.press} h-10 w-10 rounded-full border border-slate-200/80 text-2xl`}>×</button></div><RangeSlider from={from} to={to} onFrom={setFrom} onTo={setTo} /><div className="mt-2"><Search value={search} onChange={setSearch} label="Cerca squadra nella classifica completa" /></div></header>
    <div className="min-h-0 flex-1 overflow-y-auto overflow-x-hidden"><div role="table" aria-label={`Classifica Coppa giornate ${from}-${to}`} className="w-full text-[7px] min-[390px]:text-[8px] sm:text-xs"><div role="row" className="sticky top-0 z-10 grid grid-cols-[30px_minmax(70px,1.65fr)_24px_34px_repeat(5,18px)] items-center gap-px bg-slate-100 px-1 py-2 min-[390px]:grid-cols-[32px_minmax(86px,1.65fr)_26px_38px_repeat(5,20px)] sm:grid-cols-[48px_minmax(150px,1.4fr)_48px_68px_repeat(5,42px)] lg:grid-cols-[58px_minmax(260px,2fr)_70px_90px_repeat(5,minmax(54px,1fr))]">{headers.map(([label, key]) => <div role="columnheader" key={label} className={label === "SQUADRA" ? "text-left" : "text-center"}>{key ? <button onClick={() => changeSort(key)} className="w-full whitespace-nowrap font-black">{label}{sort === key ? direction === "asc" ? " ↑" : " ↓" : ""}</button> : <span className="font-black">{label}</span>}</div>)}</div>
      {shown.map((row) => { const showQualification = sort === "official" || sort === "points"; const qualificationLabel = qualificationSeparators.get(row.position); return <div key={row.id} className="relative"><div role="row" className={`grid min-h-10 grid-cols-[30px_minmax(70px,1.65fr)_24px_34px_repeat(5,18px)] items-center gap-px border-b border-slate-200/80 px-1 min-[390px]:grid-cols-[32px_minmax(86px,1.65fr)_26px_38px_repeat(5,20px)] sm:min-h-12 sm:grid-cols-[48px_minmax(150px,1.4fr)_48px_68px_repeat(5,42px)] lg:grid-cols-[58px_minmax(260px,2fr)_70px_90px_repeat(5,minmax(54px,1fr))] ${showQualification && row.position >= 65 ? "border-l-2 border-l-rose-300 bg-rose-100/60" : "bg-white"}`}><div role="cell" className="text-center"><Position row={row} /></div><div role="cell" className="min-w-0"><Team team={row} compact marquee /></div><div role="cell" className="text-center font-black">{row.points}</div><div role="cell"><Total value={row.totalPoints} min={minTotal} max={maxTotal} centered /></div>{[row.won,row.drawn,row.lost,row.goalsFor,row.goalsAgainst].map((value, index) => <div role="cell" key={index} className="text-center font-bold tabular-nums">{value}</div>)}</div>{showQualification && qualificationLabel && <QualificationSeparator position={row.position} label={qualificationLabel} />}</div>; })}
    </div></div>{sort !== "official" && <footer className="border-t border-slate-200 bg-white px-3 py-2 text-center text-[9px] font-bold text-slate-500">Vista ordinata per dato · POS conserva la posizione ufficiale</footer>}</div></div>;
}

function RangeSlider({ from, to, onFrom, onTo }: { from: number; to: number; onFrom: (day: number) => void; onTo: (day: number) => void }) { const [active, setActive] = useState<"from" | "to" | null>(null); const fromPercent = ((from - 1) / 13) * 100, toPercent = ((to - 1) / 13) * 100; return <div className="mt-1"><div className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2 text-[10px] font-black text-slate-500"><span>1</span><div className={styles.rangeTrack}><i className={styles.rangeRail}/><i className={styles.rangeFill} style={{ left: `${fromPercent}%`, right: `${100 - toPercent}%` }}/><input aria-label="Da giornata Coppa" type="range" min={1} max={14} value={from} onChange={(event) => onFrom(Math.min(Number(event.target.value), to))} onPointerDown={() => setActive("from")} onPointerUp={() => setActive(null)} className={styles.rangeInput} style={{ zIndex: active === "from" ? 4 : from >= 13 ? 3 : 2 }}/><input aria-label="A giornata Coppa" type="range" min={1} max={14} value={to} onChange={(event) => onTo(Math.max(Number(event.target.value), from))} onPointerDown={() => setActive("to")} onPointerUp={() => setActive(null)} className={styles.rangeInput} style={{ zIndex: active === "to" ? 4 : 2 }}/></div><span>14</span></div><p className="text-center text-[10px] font-black text-blue-950">Giornate {from}–{to}</p></div>; }
function QualificationSeparator({ position, label }: { position: number; label: { desktop: string; mobile: string } }) { const tone = position === 8 ? "text-amber-700 [&_i]:bg-amber-400" : position === 16 ? "text-amber-700 [&_i]:bg-amber-500" : position === 24 ? "text-orange-700 [&_i]:bg-orange-400" : position === 32 ? "text-orange-800 [&_i]:bg-orange-500" : "text-rose-700 [&_i]:bg-rose-400"; return <div role="separator" className={`pointer-events-none absolute inset-x-0 bottom-0 z-[2] flex translate-y-1/2 items-center gap-1.5 px-2 text-[7px] font-black uppercase tracking-wide sm:text-[9px] ${tone}`}><i className="h-px flex-1"/><span className="bg-[#f8fbff] px-1 sm:hidden">{label.mobile}</span><span className="hidden bg-[#f8fbff] px-1 sm:inline">{label.desktop}</span><i className="h-px flex-1"/></div>; }

function Position({ row }: { row: CoppaStanding }) { return <span className="inline-flex items-center gap-0.5 font-black tabular-nums">{row.position}<i aria-label={row.movement > 0 ? `${row.movement} posizioni guadagnate` : row.movement < 0 ? `${Math.abs(row.movement)} posizioni perse` : "Posizione invariata"} className={`text-[8px] not-italic ${row.movement > 0 ? "text-emerald-600" : row.movement < 0 ? "text-rose-600" : "text-slate-400"}`}>{row.movement > 0 ? "↑" : row.movement < 0 ? "↓" : "–"}</i></span>; }
function Total({ value, min, max, centered = false }: { value: number; min: number; max: number; centered?: boolean }) { const tone = min === max ? "text-slate-600" : value === max ? "text-emerald-600" : value === min ? "text-rose-700" : "text-slate-600"; return <strong className={`block ${centered ? "text-center" : "text-right"} whitespace-nowrap font-black tabular-nums ${tone}`}>{value}</strong>; }
function formatFantasyScore(value: number) { return Number(value.toFixed(2)).toString(); }
function Search({ value, onChange, label }: { value: string; onChange: (value: string) => void; label: string }) { return <label className="block"><span className="sr-only">{label}</span><input type="search" value={value} onChange={(event) => onChange(event.target.value)} placeholder="Cerca squadra..." className="h-11 w-full rounded-xl border border-slate-200 bg-white px-4 text-sm font-bold text-blue-950 outline-none placeholder:text-slate-400 focus:border-sky-400 focus:ring-2 focus:ring-sky-100" /></label>; }
function Team({ team, reverse = false, compact = false, marquee = true }: { team: CoppaTeam; reverse?: boolean; compact?: boolean; marquee?: boolean }) { const nameClass = `${compact ? "text-[9px] min-[390px]:text-[10px] sm:text-xs" : "text-xs sm:text-sm"} min-w-0 flex-1 font-black uppercase text-blue-950`; return <Link href={`/societa/${team.slug}`} title={team.name} className={`flex min-w-0 items-center gap-1 ${reverse ? "flex-row-reverse text-right" : ""}`}><Image src={team.logo} alt="" width={28} height={28} className={`${compact ? "h-4 w-4 sm:h-7 sm:w-7" : "h-7 w-7"} shrink-0 object-contain`} />{marquee ? <TeamMarquee name={team.name} className={nameClass}/> : <span className={`${nameClass} truncate`}>{team.name}</span>}</Link>; }
function TeamMarquee({ name, className }: { name: string; className: string }) { const viewport = useRef<HTMLSpanElement>(null), text = useRef<HTMLSpanElement>(null); const [distance, setDistance] = useState(0); useLayoutEffect(() => { const measure = () => { if (viewport.current && text.current) setDistance(Math.max(0, Math.ceil(text.current.scrollWidth - viewport.current.clientWidth))); }; measure(); const observer = new ResizeObserver(measure); if (viewport.current) observer.observe(viewport.current); if (text.current) observer.observe(text.current); return () => observer.disconnect(); }, [name]); return <span ref={viewport} className={`${styles.marqueeViewport} ${className}`} title={name}><span ref={text} style={distance ? ({ "--marquee-distance": `-${distance}px` } as CSSProperties) : undefined} className={`${styles.marqueeText} ${distance ? styles.marqueeActive : ""}`}>{name}</span></span>; }
function Empty({ text }: { text: string }) { return <p className="rounded-2xl border border-dashed border-slate-300 bg-slate-50 p-5 text-center text-xs font-bold text-slate-500">{text}</p>; }
